### ISSUE TITLE
Selbstregistrierung: Anzahl der Teilnehmenden limitieren

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#103]
Die neue Funktion der Selbstregistrierung für eine Konferenz ist toll.

Da einige Server jedoch limitierte Ressourcen haben oder das Konzept der Gruppenarbeit keine unbegrenzte Zahl ermöglicht (erwünscht), wäre es toll, wenn man die Anzahl der Selbstregistrierungen begrenzen könnte.

**Comment by AlexanderGabriel** [comment]
+1
