### ISSUE TITLE
I need some clarifications

### ISSUE THREAD

**Issue by WhiteTiger-IT** [H2-invent/jitsi-admin#108]
Hi,
in the requirements there is Apache, but Jitsi is installed with Nginx.
I have used this [script](https://github.com/emrahcom/emrah-tools/tree/main/jitsi/installer/buster).
Or maybe Jits admin needs to be installed on a different server?
What modules should then be provided for php?
Thanks in advance.

**Comment by AlexanderGabriel** [comment]
I have Jitsi and JitsiAdmin on my private server both running with Apache.
This is possible if you install apache before jitsimeet but maybe too late now for you.
At work we have different servers.
Never ran nginx with php so i can't answer your second question. Sorry.

**Comment by WhiteTiger-IT** [comment]
Thank you for your answer
I am still in a test environment and have no problem doing a fresh install of Jitsi Meet.
But I see that there is always talk of installations with Nginx, I don't see documentation to use Apache.
In any case my question is whether Jitsi Admin should be installed on the same server or on another server.
I have a second server with Apache

**Comment by holzi1005** [comment]
Hi @WhiteTiger-IT 
It is possible to use nginx with Jitsi Admin,
you have to setup __php-fpm__ as well on the server and use it as a backend for NGINX. With this method, you can install Jitsi Meet and Jitsi Admin on one server.
Here is an example from another website: https://www.journaldev.com/26097/php-fpm-nginx

**Comment by holzi1005** [comment]
> Thank you for your answer
> I am still in a test environment and have no problem doing a fresh install of Jitsi Meet.
> But I see that there is always talk of installations with Nginx, I don't see documentation to use Apache.
> In any case my question is whether Jitsi Admin should be installed on the same server or on another server.
> I have a second server with Apache

I would not recommend using Apache for Jitsi Meet.
You have to use NGINX for Jitsi Admin. This way it will work.

**Comment by holema** [comment]
@WhiteTiger-IT could we help you with these answers?

**Comment by holema** [comment]
hello @WhiteTiger-IT 

was the installation of the Jits-Admin sucessfully?
