### ISSUE TITLE
timediff in Kalender

### ISSUE THREAD

**Issue by osnet** [H2-invent/jitsi-admin#127]
Servus, 
ein gutes Stück Software hats ihr hier geschrieben ! top. 

Ich habe soweit alles fertig und am laufen. 
Ich habe nur ein Problem. die Einladungen der Konferenztermine  werden  zu 100% nur in den emails an sich korrekt angegeben.
die ICS daten laufen aber irgendwie aus dem ruder.  diese sind momentan 2h n der zukunft. 

Kann man irgendwo in dem symphony oder nodejs  die richtige zeit  mit gewalt angeben ? : ) 

dankee

**Comment by holema** [comment]
Hallo @osnet 
Das Problem können wir leider nicht nachvollziehen. Ich habe gerade nochmal nachgeschaut und bei mir sind auch im ICS die Zeiten korrekt gesetzt.
Kannst du mir mal eine solche Einladung an entwicklung@h2-invent.com weiterleiten?

VG

**Comment by holema** [comment]
@osnet ich habe gerade gesehen das du aus Tölz kommst, ich bin direkt aus dem Nachbarort. :)

**Comment by osnet** [comment]
@holema 
an schaaß ...  Fehler gefunden,  ist nicht  h2 : ) 
zur info : https://github.com/mlan/docker-kopano/issues/24

**Comment by holema** [comment]
@osnet 
Hast du den Jitsi-Admin in einem Docker Container zum laufen bekommen? Und könntest du etwas darüber berichten wie du das gemacht hast?

**Comment by osnet** [comment]
@holema 
lesen ...  : )
ne  jitsi-admin  läuft nativ auf  centos8 stream
ich habe festgestellt das unser mailserver  der im docker läuft zwar mit timezones umgehen kann aber localtime nicht CEST ist sondern UTC,  obwohl  nach vorschrift  reingemounted. 
hier muss ich mit mlan was erfinden das auch der mailserver  das richtig macht. 
ihr seids da aussen vor. 

AABER  mein cheffe wollte eh das ich  euren jitisi-admin in nen docker verwandle. 
wird wohl nen grösserer act nach dem ich gesehen habe was ich auf der "dedizerten"  vm schon alles machen musste  : P

vielleicht in den nächsten  paar wochen

**Comment by klepptor** [comment]
Eine Docker Version von jitsi-admin wäre tatsächlich ein Traum!

**Comment by osnet** [comment]
@holema 
zu deiner info.  ich habe bei uns den fehler gefunden.  ist  z-push  was nicht korrekt mit  TZ environments arbeitet. 
weiss der geier  wie ich dem  europe/berlin verklickern soll.  : )

**Comment by AlexanderGabriel** [comment]
DA muss nur "Europe/Berlin" in der config stehen... Einfach so eintragen. Hatte z-push erst diese Woche in der Hand und hab genau das eingetragen. Bin jetzt nicht mega-qualifiziert aber probier's einfach mal.
