### ISSUE TITLE
Alle unsere Konferenzen sind verschwunden

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#136]
Hallo,
als ich mich grade eingeloggt habe, sind alle unsere Konferenzen verschwunden? Samt Adressbuch, Anmeldungen und Archiv?

**Comment by xdaniel2063** [comment]
Die Anmeldeseiten sind noch vorhanden.

**Comment by holema** [comment]
Es ist alles wieder da @xdaniel2063 Das war ein Bug der durch das neue Feature kam

**Comment by xdaniel2063** [comment]
Danke sehr. Hatte schon einen kleinen Schock bekommen, dann aber vertrauen gehabt.

**Comment by holema** [comment]
@xdaniel2063 Das neue Feature entschädigt dafür sicher :) Das ist eine Mischung aus jitsi und Doodle

**Comment by xdaniel2063** [comment]
@holema  ja, sieht gut aus.
