### ISSUE TITLE
Email settting - calendar

### ISSUE THREAD

**Issue by namtel-hp** [H2-invent/jitsi-admin#138]
Dear,
I try to setting email but when add participants can not send to:
I try set sendmail localhost and cloud mail but not working.
my .env.local
###> symfony/swift_mailer ###
MAILER_HOST=us2.smtp.mailhostbox.com
MAILER_PORT=587
MAILER_PASSWORD=hide23%
MAILER_USERNAME=support%40saza.vn
MAILER_ENCRYPTION=tls
MAILER_TRANSPORT=smtp
OR OR
MAILER_URL=smtp://us2.smtp.mailhostbox.com:587?encryption=tls&username=support%40saza.vn&password=hide32%...
 OR
MAILER_DNS=smtp://us2.smtp.mailhostbox.com:587?encryption=tls&username=support%40saza.vn&password=hide32%...
Not work, please help.

Second:
Create Room: on the Meet Admin are numbers like: https://meet.jit.si/09846786768
But when see on the calendar are characters like: https://meet.jit.si/ahsjsjhdhgahaHTsh
so if room is public still can not join.

admin@admin:/srv/admin$ php bin/console config:dump-reference swiftmailer
# Default configuration for extension with alias: "swiftmailer"
swiftmailer:
    default_mailer:       ~
    mailers:

        # Prototype
        name:
            url:                  null
            transport:            smtp
            command:              '/usr/sbin/sendmail -t -i'
            username:             null
            password:             null
            host:                 localhost
            port:                 null
            timeout:              30
            source_ip:            null
            local_domain:         null
            stream_options:       []
            encryption:           null
            auth_mode:            null
            sender_address:       ~
            delivery_addresses:   []
            antiflood:
                threshold:            99
                sleep:                0
            logging:              true
            spool:
                type:                 file
                path:                 '%kernel.cache_dir%/swiftmailer/spool'

                # Used by "service" type
                id:                   null
            delivery_whitelist:   []
            disable_delivery:     ~

admin@admin:/srv/admin$  php bin/console debug:config swiftmailer

Current configuration for extension with alias "swiftmailer"
============================================================

swiftmailer:
    default_mailer: default
    mailers:
        default:
            spool:
                type: memory
                path: '%kernel.cache_dir%/swiftmailer/spool'
                id: null
            disable_delivery: false
            host: '%env(MAILER_HOST)%'
            password: '%env(MAILER_PASSWORD)%'
            username: '%env(MAILER_USERNAME)%'
            transport: '%env(MAILER_TRANSPORT)%'
            encryption: '%env(MAILER_ENCRYPTION)%'
            port: '%env(MAILER_PORT)%'
            url: null
            command: '/usr/sbin/sendmail -t -i'
            timeout: 30
            source_ip: null
            local_domain: null
            stream_options: {  }
            auth_mode: null
            delivery_addresses: {  }
            logging: true
            delivery_whitelist: {  }
Please help 

My question are: set on Sympony or App ? what's wrong?

I already install sendmail -local:
dmin@admin:/srv/admin/config/packages$ netstat -an | grep 587
tcp        0      0 0.0.0.0:587             0.0.0.0:*               LISTEN     
tcp6       0      0 ::1:587                 :::*                    LISTEN     
admin@admin:/srv/admin/config/packages$ 

admin@admin:/srv/admin/config/packages$ netstat -an | grep 465
tcp        0      0 0.0.0.0:465             0.0.0.0:*               LISTEN     
tcp6       0      0 ::1:465                 :::*                    LISTEN     
admin@admin:/srv/admin/config/packages$ 

Thanks for support.

**Comment by holema** [comment]
We look at the logs and see that it is no error of the jitsi-admin. It´s a SMTP-Server issue resp. a TLS-issue

**Comment by namtel-hp** [comment]
Dear,

Thanks for support,
email : worked now



Sent from myMail for iOS


Wednesday, April 14, 2021, 11:30 PM +0700 from ***@***.***  ***@***.***>:

**Comment by namtel-hp** [comment]
Dear,
Thanks for support,
Email: worked already
- Jwt enable: meet can not recording and live stream. 
Thanks



Sent from myMail for iOS


Wednesday, April 14, 2021, 11:30 PM +0700 from ***@***.***  ***@***.***>:
