### ISSUE TITLE
Felder für E-Mails in Enterprise-Version

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#139]
Ich habe heute in den Enterprise-Einstellungen auf jitsi-admin.de zwei neue Felder entdeckt:
* Individuelle Überschrift für E-Mails und 
* Individueller Content

Wo genau werden diese Felder verwendet und in welchen E-Mails?

**Comment by holzi1005** [comment]
Hi @xdaniel2063,

stimmt, diese Felder haben wir noch gar nicht beschrieben.
* 1 = Überschrift
* 2 = Content

Diese Angaben werden in allen Emails (Einladung, Benachrichtigung,...) verwendet.


![Bild1](https://user-images.githubusercontent.com/58698758/114753394-b471bb00-9d57-11eb-99ac-7866941f270f.png)

**Comment by xdaniel2063** [comment]
Danke für die Erklärung. Kann man in dem E-Mail-Content auch Markdown nutzen, wie in der Agenda?
