### ISSUE TITLE
Set meetingroom password 

### ISSUE THREAD

**Issue by raphi59** [H2-invent/jitsi-admin#140]
Hi Guys,

It would be nice to have a button like "set meeting room password" in the create conference form.
I haven't seen this were already implemented.

**Describe the solution you'd like**
Have a "set meeting room password" checkbox and enter password for the room.

**Additional context**
I've seen some discussions about a persistent-password lua script for prosody in the jitsi forum, probably it's easier to just implement a "trigger" in jitsi-admin to the lua script. So with the checkbox and input box in Jitsi-Admin you pass your password to the lua script. Is maybe something like this possible?

**Comment by holema** [comment]
Hallo @raphi59 
Aber dann haben wir doch wieder jitsi in seiner ursprünglichen Form.
Du kannst ja auch bei Jitsi einfach ein Passwort für einen Raum hinterlegen.
Wir verhindern ja durch den Login mit der Email einen unberechtigten Beitritt.
Wenn du es noch weiter Absichern willst, dann kannst du die Option: **Nur registrierte Benutzer dürfen der Konferenz beitreten** in den erweiterten Optionen aktivieren.
dadurch muss jeder User einen Account haben um beitreten zu dürfen. Somit kann ein User nicht mal bei bekanntwerden des Links eine Chance der Konferenz beizutreten.
