### ISSUE TITLE
No route found for "GET /addHere/auth/realms/addHere/protocol/openid-connect/auth"

### ISSUE THREAD

**Issue by ayushsaraswat92** [H2-invent/jitsi-admin#142]
After succesfull install while run localhost, I got this error, How to bypass this?

**Comment by holema** [comment]
hello @ayushsaraswat92 
You need to set the keycloak settings in the .env.local correctly. this ist the keycloak url and the keycloak realm.

**Comment by holema** [comment]
@ayushsaraswat92 is the issue solved?

best regads Emanuel

**Comment by ayushsaraswat92** [comment]
Actually, its stuck on some another error its now displays "Invalid Parameter : redirect_uri"

**Comment by holema** [comment]
what is written in the redirect_uri on the keycloak request? It must be somewhere in the request when the Jitsi-Admin redirects to the keycloak.

best regardds.

**Comment by ayushsaraswat92** [comment]
Oh, yes silly me. Forget to add the valid redirect URI in realms settings.

**Comment by holema** [comment]
hey @ayushsaraswat92 
So everything is working now? then we can close it :)

**Comment by ayushsaraswat92** [comment]
Yes, everything is going good
