### ISSUE TITLE
Enterprise-Version: Statistiken können nicht mehr eingesehen werden

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#145]
Der Button Einstellungen -> Statistiken verweist auf die Seite Enterprise-Einstellungen bzw. manchmal färbt sich nur der Hintergrund grau ein. Aktuelle Firefox-Version. https://i.imgur.com/4k4YkNU.png

**Comment by holema** [comment]
@xdaniel2063 danke für den Hinweis schauen gerade die logs an. Das komische ist, das nur manche Server betroffen sind. Wir werden aber heute noch einen Bugfix veröffentlichen.

**Comment by xdaniel2063** [comment]
danke sehr :-)
