### ISSUE TITLE
Teilnehmer im Nachhinein anmailen

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#147]
Wir haben oft die Situation, dass wir nach einer Veranstaltung die Teilnehmenden nochmals anmailen möchten bzw. etwas versprochen haben. Dies kann beispielsweise sinnvoll sein, um eine Präsentation nachzureichen oder andere Informationen im Nachgang zu übermitteln.

Wäre es möglich entweder eine direkte Kommunikation einzubauen oder die Teilnehmenden nachträglich zu exportieren? Ich weiß nicht, ob das ein Datenschutzproblem ist?

**Comment by holema** [comment]
@xdaniel2063 
Die Idee ist wirklich gut und wir stellen sie mal auf unsere Roadmap.

**Comment by xdaniel2063** [comment]
@holema wo ist denn die Funktion versteckt? :-)
