### ISSUE TITLE
Mehrteilige Konferenzen

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#148]
Wünschen darf man sich ja viel, auch wenn kein Weihnachten ist.

Wir führen auch öfters mehrteilige Web-Workshops durch und da wäre es klasse, wenn man die Anmeldefunktion auch dafür nutzen könnte? Also wenn man eine Konferenz eingeben könnte, die auf mehrere Daten verteilt ist. Beispielsweise Mittwoch, 9.00 Uhr, Freitag 11.00 Uhr oder ähnliches auch an drei oder mehr Terminen.

Vielleicht wäre das auch ein zusätzlicher Anreiz für die Enterprise-Version.

**Comment by xdaniel2063** [comment]
Etwas ähnlich wären auch wiederkehrende Termine, also jeden Mittwoch 19.00 Uhr oder ähnliches.

**Comment by holema** [comment]
@xdaniel2063 Also bei mehrteiligen Terminen kannst du einfach den Termin duplizieren und die Zeit neu setzen. Dann werden alle Settings und die Teilnehmer kopiert.

Wiederholende Termine sind auf der Roadmap.

**Comment by holema** [comment]
@xdaniel2063 
in der neuen Version haben wir die weiderholenden Termine eingebaut. Ich denke das wird dir gefallen.
Die Version sollte morgen online gehen. Dann kannst du sie ausgiebig testen und Fehler melden ;)
