### ISSUE TITLE
Univention OIDC Authentifizierung

### ISSUE THREAD

**Issue by raphi59** [H2-invent/jitsi-admin#156]
Ich verwende in meiner Umgebung einen Univention als IdP für OIDC. 
Die Authentifizierung damit funktioniert leider wegen der oauth-keycloak Libary nicht, wäre schön, support auch für andere IdPs als Keycloak ein zu bauen.

**Comment by holema** [comment]
Hallo @raphi59 
Wir verwenden dieses Bundle für die Integration in den Jitsi-admin.
https://github.com/knpuniversity/oauth2-client-bundle
Alle in dem Github Repo angegebene Provider (ganz unten bei dem Link) kann man mit überschaubarem Aufwand einbauen.


Viele Grüße

**Comment by holema** [comment]
Hello @raphi59,
We are currently working on a UCS app integration.
