### ISSUE TITLE
Anzahl der max. Plätze auf dem Dashboard anzeigen

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#157]
Ich fnde es gut, wenn ich bei Veranstaltungen auf dem Dashboard sehen könnte, wieviele Plätze von X belegt sind.
Also beispielsweise 10 von 20. Siehe Bild: https://i.imgur.com/FQgF2kT.png

**Comment by holema** [comment]
Hall @xdaniel2063 
das klingt nach einer guten Idee. Ich denke in den nächsten Releases können wir das mal einbauen. :)

**Comment by xdaniel2063** [comment]
Dann danke ich schon Mal. Der Jitsi-Admin wird immer besser. Das macht Freude damit zu organisieren.
