### ISSUE TITLE
Anmeldeformular automatisch schliessen

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#166]
Im Moment ist es so, dass wenn die maximale Teilnehmerzahl erreicht ist, das Formular noch erscheint. Anschließend geben Interessierte Ihre Daten ein, und dann erst erfolgt die Meldung, dass keine Plätze mehr frei sind. Das ist verwirrend.

Meines Erachtens sollte die Meldung gleich erscheinen und das Formular ausgeblendet werden?

**Comment by holema** [comment]
@xdaniel2063 
Es ist so, dass unten in Rot eingeblendet wird, das die Teilnehmerzahl bereits erreicht ist. Und ja man kann weiterhin seine Daten eingeben. Das müssen wir mal diskutieren, ob das eine gute Idee ist.
@AlexanderGabriel vielleicht kannst du dazu was sagen. :)

**Comment by xdaniel2063** [comment]
Nur zur Klarstellung, bevor ich verwirre :-) Warum wird ein Formular angezeigt, wenn dessen ausfüllen keine Bedeutung hat?

Also eigentlich wollte ich vorschlagen, dass Formular bei Erreichen der max. Teilnehmerzahl gar nicht mehr zu zeigen und stattdessen die Meldung "Leider ist keine Anmeldung mehr möglich, da die max. Teilnehmerzahl erreicht ist.".

**Comment by AlexanderGabriel** [comment]
Hab ich selbst noch nicht nachvollzogen, hab eben Feierabend gemacht, kanns mir aber morgen mal anschauen.
So wie @xdaniel2063 das beschreibt wär's schon sinnvoll beim Verwenden des Direktlinks gleich zu zeigen, dass keine Plätze mehr sind und das Formular gar nicht erst anzuzeigen.
Wie verhält sich das auf der Join-Seite? Verschwindet die Veranstaltung dann oder kommt auch ein Hinweis, dass voll ist?

Noch cooler: Wie wärs mit einem Haken: "Bitte auf die Warteliste nehmen". Danach erscheint das Formular wieder ;)

**Comment by holema** [comment]
@AlexanderGabriel @xdaniel2063 
Ich habe das Feature umgesetzt und in Version 0.64.1 umgesetzt.
Es werden nun immer die freien Plätze oben unter dem Datum angezeigt.
![image](https://user-images.githubusercontent.com/22790152/116608493-884b6200-a933-11eb-9a0a-8187f557d223.png)
Hier ist noch ein Platz frei.
![image](https://user-images.githubusercontent.com/22790152/116608590-ab761180-a933-11eb-9cf9-e05448e47389.png)
Es wird kein Formular mehr angezeigt.

Noch gibt es keine Warteliste, aber ich werde mir Gedanken machen wie das umzusetzen ist.

**Comment by holema** [comment]
@xdaniel2063 
Es gibt nun eine Warteliste Funktion. Diese kann bei einem Raum unter den erweiterten Optionen angehakt werden.

Teilnehmer schreiben sich dann auf die Warteliste ein und können von dem Moderator händisch auf die Teilnehmerliste übertragen werden.
Die Wartelistenkanditaten werden bei einem klick auf die Teilnehmer unter den aktiven Teilnehmern angezeigt.

**Comment by xdaniel2063** [comment]
Die Wartelistenfunktion ist toll. Ggf. wären ein paar kleine Usability-Korrekturen sinnvoll.
a) Ich würde das Warteliste auf der Seite deutlicher kennzeichnen.
b) Die Erfolgsmeldung zum Eintrag lautet "Sie haben sich erfolgreich angemeldet.
Das könnte man noch schärfen.

**Comment by xdaniel2063** [comment]
https://i.imgur.com/dTd6V6F.png
