### ISSUE TITLE
Disable mail functions and use real names instead of email-address

### ISSUE THREAD

**Issue by d-patch** [H2-invent/jitsi-admin#184]
First of all, thanks for this cool project! We are currently evaluating it for our internal Jitsi infrastructure. So far it works really great.

In our current project, it is not foreseen to interconnect the jitsi-admin server with a mailserver at all. Also, we are only using it internally, so every user of the jitsi- and jitsi-admin-server will be authorized via keycloak, no guests or anonymous users. Because don't use mails in this system,  it is "confusing" for the user to enter the mail-address, whenever we create a meeting with jitsi-admin and want to add participants to the meeting. Therefore I would like to place this feature request for jitsi-admin to be able to use real names of the users in the addressbook instead of the mail-address (or in addition or configurable).
Also, it would be great if the mail functions of jitsi-admin could be disabled alltogether (maybe configurable in the .env file), so that there would be no more errors and warnings when an email could not be sent (because we haven't configured a mail-server ;-)

**Comment by holzi1005** [comment]
Hi @d-patch,

for this request, please send us an message via our contact form on the website, so we can contact you directly.
https://h2-invent.com/kontakt
