### ISSUE TITLE
Syncronize addressbook with keycloak

### ISSUE THREAD

**Issue by d-patch** [H2-invent/jitsi-admin#185]
As described in #184 we are currently using jitsi-admin in an internal-only way, no guests or anonymous users. Therefore all users of the jitsi-server are already available in the keycloak directory.
I would like to make the feature request for jitsi-admin, to be able to import/syncronize the user-list of keycloak to the addressbook of jitsi-admin.

**Comment by holema** [comment]
this is now done via direct sync to a LDAP server. So just enter the LDAP crendentials and sync all your users directly into the jitsi-admin. The users in the jitsi-admin and the keycloak are now synced.
