### ISSUE TITLE
SMTP issues

### ISSUE THREAD

**Issue by timololipop** [H2-invent/jitsi-admin#187]
Hey,

when I access my configured Domain in the Apache Virtual Host, it redirects me to keycloak and throws me an Invalid parameter: redirect_uri error. Any idea how I have to set the redirect url?

Thanks.

**Comment by holema** [comment]
@timowevel03 
You have to set the keycloak URL in the .env.local.
This error was here diskussed.
#142 
You have to add the allowed redirect URLs in Keycloak

**Comment by timowevel03** [comment]
redirect_uri isnt the problem anymore, I receive the error above. All URLs are set.

**Comment by holema** [comment]
hey @timowevel03 
The problem seems to me, that your apache mod_rewrite is not correct set.
in you log there ist url/index.php written.
This is normaly not necessary, when apach is set up coeect, because the index.php is not triggered directly. it ist only used to rewrite the route.
And I think that you keycloak sends the wrong informations like email to the jitsi-admin. That´s the reason why it is null, because the jitsi-admin gets no email from the keycloak.

**Comment by holema** [comment]
Is you problem solved?

**Comment by timowevel03** [comment]
Not yet, I will try it

**Comment by timowevel03** [comment]
I am a bit desperated right now. I also enabled mod_rewrite, Server Error 500. Where exactly can I get logs from?

**Comment by timowevel03** [comment]
Okay, got it working by installing another php extensions. It seems to work now, but I got the issue that the text is white and the background also, so you cannot see it that good. See here:
https://prnt.sc/13508el

**Comment by timowevel03** [comment]
Keycloak seems to work, I got my Mail at https://www.ionos.de/hilfe/e-mail/allgemeine-themen/serverinformationen-fuer-imap-pop-und-smtp/
Tried all ports, SSL, TLS, nothing works. Keycloak Email sending works fine.

**Comment by timowevel03** [comment]
My SMTP settings: 
MAILER_HOST=smtp.ionos.de
MAILER_PORT=587
MAILER_PASSWORD=MyPassword
MAILER_USERNAME=mail@timowevelsiep.de
MAILER_ENCRYPTION=tls
MAILER_TRANSPORT=smtp

**Comment by holema** [comment]
Do you work in dev or debug mode?
This is your error: Exception occurred while flushing email queue: Expected response code 250 but got code "550", with message "550-Requested action not taken: mailbox unavailable 550 invalid DNS MX or A/AAAA resource record "

I think that you run it in debug mode and forgot to set the delivery Email
This has to be set in the env with 
**DEV_EMAIL=***@***.de**

This are my SMTP settings:
They look quite similar.
MAILER_HOST=******.kasserver.com
MAILER_PORT=587
MAILER_PASSWORD=**********
MAILER_USERNAME=m**********
MAILER_ENCRYPTION=tls
MAILER_TRANSPORT=smtp

**Comment by timowevel03** [comment]
In .env or also .env.local?

**Comment by holema** [comment]
Only touch the .env.local file.
The .env local holds the fdefault values and these values will be overwritten by the local env.

When you switch to prod mode, you need to make a cach:clear and cache:warmup to prepare the cache for sysmfony.

If it doesn`t work, you can contact us via our contactform. https://h2-invent.com/kontakt

Best regards

**Comment by timowevel03** [comment]
It is fixed, thanks.

**Comment by bienxanh1901** [comment]
> Okay, got it working by installing another php extensions. It seems to work now but I got issues with smtp setup. Which encryption types are supported?

hello @timololipop,
I am facing with same problem **500 internal server error.**
How do you solve it?
I'm current using php7.4-fpm

Thank you!

**Comment by timololipop** [comment]
Hey, I just used an older version of Jitsi Admin.
________________________________

**Comment by bienxanh1901** [comment]
@timololipop thank you so much.
The version 0.70.7 worked for me.
For latest version 0.71.9, I got issue: ERR_TOO_MANY_REDIRECT

**Comment by timololipop** [comment]
Yes, had the same issue
________________________________

**Comment by holema** [comment]
Hello @timololipop and @bienxanh1901,

sorry for the late replay, I got no notifivcation that you wrote in the old issue.

The ERROR with the TOO_MANY_REDIRECTS is very strange. 
Did you try to fix it with clearing all your browser cache?
What happens when you switch on the dev mode? Thiy you can do by setting the env variable APP_ENV=dev and APP_DEBUG=1.
Then you have a debug console and probaly more informations.
Or you can write me the URL to the server to entwicklung@h2-invent.com and I can have a look.

For the SMTP stuff, you can set the SMTP Settings here in the .env.local file
###> symfony/swift_mailer ###
MAILER_HOST=serverHost
MAILER_PORT=587
MAILER_PASSWORD=Password
MAILER_USERNAME=Username
MAILER_ENCRYPTION=tls
MAILER_TRANSPORT=smtp

I hope this helps you to configure the SMTP correctly.

**Comment by holema** [comment]
hello @bienxanh1901,

I just talked to a collegue, and he told me that is importent that you install php7.4-ldap extension.

**Comment by bienxanh1901** [comment]
> 

Do you mean we should remove php-ldap extension?

**Comment by holema** [comment]
@bienxanh1901, no, it has  to be installed to get composer run. BEcause the Jitsi-Admin is now directly connectable with a LDAP

**Comment by bienxanh1901** [comment]
> @bienxanh1901, no, it has to be installed to get composer run. BEcause the Jitsi-Admin is now directly connectable with a LDAP

Hello! I have installed php7.4-ldap extension, It still got error TOO_MANY_REDIRECTS  after login.
I currently using keycloak to authenticate to jitsi admin. 
Does it conflict with the LDAP feature in the new release?

**Comment by holema** [comment]
Hallo @bienxanh1901 
The LDAP Feature is comletly independen of the Keycloak.
You still need the keycloak to authenticate to the jitsi-admin.
can you post the env.local Kecloak part here, with blacked client-secret? Then I can have a look if there is womething wrong.

Have you set up the groups the correct way?
You have to set them up as here described
https://github.com/H2-invent/jitsi-admin/wiki/Organize-Jitsi-Servers-via-keycloak-groups

**Comment by bienxanh1901** [comment]
> Hallo @bienxanh1901 The LDAP Feature is comletly independen of the Keycloak. You still need the keycloak to authenticate to the jitsi-admin. can you post the env.local Kecloak part here, with blacked client-secret? Then I can have a look if there is womething wrong.
> 
> Have you set up the groups the correct way? You have to set them up as here described https://github.com/H2-invent/jitsi-admin/wiki/Organize-Jitsi-Servers-via-keycloak-groups

Hi @holema 
this is keycloak config:

###> hwi/oauth-bundle ###
OAUTH_KEYCLOAK_CLIENT_ID=jitsi
OAUTH_KEYCLOAK_CLIENT_SECRET=<MY_SECRET>
OAUTH_KEYCLOAK_SERVER=http://localhost:8080/auth
OAUTH_KEYCLOAK_REALM=jitsi
###< hwi/oauth-bundle ###


**Have you set up the groups the correct way?**
Yes. I have set up the groups correct. In Release 0.70.7 it works perfectly with same config
I have tried to use latest release 0.71.13 but still get error TOO_MANY_REDIRECTS after login.

Thank you

**Comment by holema** [comment]
See #259

**Comment by holema** [comment]
closed in #259
