### ISSUE TITLE
Kleine Wünsche zur optimaleren Nutzung

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#188]
Liebes Jitsi-Admin Team,

Das ganze wird immer runder und besser. Mir macht die Arbeit mit dem Tool viel Freude!

Ich möchte noch ein paar kleinere Anpassungen vorschlagen:

* Warte liste: Könnte "Warteliste" oben auf der Seite deutlicher gekennzeichnet werden, wenn das Seminar voll ist?
* Warteliste: Die Erfolgsmeldung zum Eintrag lautet "Sie haben sich erfolgreich angemeldet." Besser wäre: "Sie wurden erfolgreich in die Wartelliste eingetragen".
* Es gibt die Unterscheidung Moderator und Organisator. In der Liste der Veranstaltungen wird der Organisator als Moderator ausgewisen.
* Wäre es möglich, dass auch Moderatoren die Teilnehmerliste einsehen können? Dies ist beispielsweise zur Vorbereitung auf die Gruppe sinnvoll.
* Die Einstellung der möglichen Dauer eines Seminars ist sehr unflexibel. Vor allem der Sprung von zwei auf vier Stunden. Könnte man hier nicht den 15 Minuten-Rhythmus durchhalten oder die Eingabe in Minuten ermöglichen?

Viele Grüße
Daniel

**Comment by holema** [comment]
Hallo @xdaniel2063,
zu 1.
Das kommt auf die ToDo Liste, da dies kein großer Change ist.
zu 2.
Der Teilnehmer hat sich auch erfolgreich angemeldet. Ein Zuordnung zur Warteliste geschieht erst nach dem Opt-In. Unter umständen wurde ein Teilnehmer entfernt, bevor der neue Teilnehmer den Opt-In bestätigt und damit wird er nicht der Warteliste zugeordnet. Der Teilnehmer erhält aber nach dem Opt-In eine Email, in der steht das es auf der Warteliste ist.
zu4.
Das müssen wir ändern. Danke für den Hinweis
zu5.
Das könnte ein DSGVO Problem werden, da dadurch auch Emailadressen nicht nur dem Organisator zugänglich sind.
zu6.
Das ist etwas, das mach auch auf die Todo Liste. Wie wir es umsetzen, das muss noch abgestimmt werden, oder es gibt von dir eine Idee :)

**Comment by xdaniel2063** [comment]
Muchas Gracias. 

1. Die DSGVO möchte ich ja nicht in Frage stellen :-), **wenn man das nicht darf, ist alles gut**. In der Praxis dürfte es so sein, dass viele Seminare von mindestens zwei Personen durchgeführt werden (ich bin der Erwachsenenbildung tätig). Manchmal sogar drei, wenn einer noch den Chat im Auge behält oder Tech-Support bietet. Der Organisator ist ja eigentlich der Veranstalter (technisch derjenige, der die Veranstaltung anlegt) und meistens auch Impulsgeber.  In der Seminarvorbereitung interessiert tatsächlich immer, wie die Gruppe zusammengesetzt ist, auch von welchen Organisationen die Leute kommen. 

2. zu den zeitlichen Intervallen: Die 15 Minuten-Taktung finde ich ok. Kann man nicht einfach in der Auswahl-Liste weitere Items hinzufügen? Ich denke länger als 8 Stunden ist kein Webinar. Wir machen schon mal drei Stunden Meetings, da ist aber dann eine 30 Minütige Pause drin. Eine Tagung dauert schon mal 6 Stunden inkl. Pausen.
Wenn man dann noch eine viertel Stunde vorher öffnet und eine halbe zum Netzwerken hinten drauf legt, ist die 8 fast erreicht. Meine Kinder sind in der Ganztagsschule, die sind manchmal von 8.00 bis 16.00 Uhr on.

Sind alles nur Ideen und Gedanken.

**Comment by AlexanderGabriel** [comment]
Wir werden in das Problem von mehreren Organisatoren wohl auch rein rennen, werden das aber wohl mit Funktions-Adressen (abteilungsname@example.com) lösen. Damit loggt man sich ein und alle Sachbearbeiter können kann verwalten. Eine Option, einen anderen Teilnehmer auch zum Organisator zu machen wäre natürlich super aber der Workaround tut's für uns auch. DSGVO sehe ich bei uns nicht als Problem, weil das ja die Person abwägen kann, die den Knopf drückt. Ob in der einen Abteilung nun nur einer oder zwei Mitarbeiter, die aber beide das gleiche berechtigtes Interesse an den Daten haben Zugriff haben macht hier keinen Unterschied. Und wer Organisiert muss ja wissen, wen er evtl. hinzufügt oder runter nimmt oder anschreibt, weil sich irgendwas verändert ;)

**Comment by xdaniel2063** [comment]
Gibt es weitere Unterschiede in den beiden Rollen? Ist der Organisator auch gleichzeitig Moderator im Jitsi-Meeting?

**Comment by AlexanderGabriel** [comment]
Jitsi selbst kennt die Rolle Organisator gar nicht. Für das ist das ein Moderator.

**Comment by holema** [comment]
@xdaniel2063 Ja ein Organisator ist auch immer gleichzeitig Moderator bei Jitsi.
Wir geben dem Organisator und allen bestimmten Moderatoren das Attribut Moderator im JWT mit.

Im Jitsi-Admin kann ein Organisator alles Bearbeiten, ein Moderator ist lediglich im Jitsi-Meet Meeting mit den Moderatoren Rechten ausgestattet.

**Comment by holema** [comment]
@AlexanderGabriel das ist bei euch der Fall, das es kein Problem, wie müssten das aber in der public Version ausschalten, da ich ja sonst die betroffene Person (den Menschen, der sich gerade anmeldet) darüber informieren das auch andere, als der Organisator, seine Daten sehen könnten.

Ich lass das mal prüfen wie das ein Datenschützer sieht :) @holzi1005 


Das ein Moderator auch andere Berechtigungen bekommen soll wie ein Organisator. -->  das müssten wir mal durchdenken, aber wir haben damals leider das so nicht eingeplant und das könnte nun tatsächlich einen größeren Umbau bedeuten. Da es pro Raum nur einen Organisator gibt (kein Array) das müsste dann überall abgefragt werden, wo Organisatorenrechte benötigt werden.

**Comment by holema** [comment]
@xdaniel2063 
Es sind jetzt eigentlich alle deine Wünsche umgesetzt bzw. behoben.
Außer das Thema mit der Teilnehmerliste einsehen.
Das ist wirklich aus der DSGVO Sicht in einem geteilten Jitsi-Admin ein Problem. In einem Enterprise Jitsi-Admin, also selfhosted wäre das eine gute Erweiterung und auch einfach umsetzbar, aber dafür müsste der FR von einem Unternehmen kommen, da dies doch etwas aufwand bedeutet. 
Aber es steht auf der Rodmap.
