### ISSUE TITLE
Help with nginx

### ISSUE THREAD

**Issue by timowevel03** [H2-invent/jitsi-admin#190]
Hello!

I try to use nginx instead of Apache2 but I run into some issues. I also follwed the steps of another issue, all php extensions are installed, php-fpm is configured with nginx. 
The project has an .htaccess file which has to be converted probably because when I set my public folder as root and index index.php, I get a 404.

`"/var/www/jitsi-admin/public/room/dashboard" failed (2: No such file or directory),`

Has anyone a nginx config which works?

Thanks.

**Comment by Meriemi-git** [comment]
Hi !
I have the same problem,
Jitsi use nginx by default so it will be really appreciate to have the equivalent configuration.

Thanks.

**Comment by holzi1005** [comment]
Hi @timowevel03 @Meriemi-git 
you can use a normal Symfony 5 php-fpm config to get it running with nginx.

```
server {
   server_name your-server-ip;
   root /var/www/jitsi-admin/public;
   location / {
       try_files $uri /index.php$is_args$args;
   }
   location ~ ^/index\.php(/|$) {
       fastcgi_pass unix:/var/run/php/php7.4-fpm.sock;
       fastcgi_split_path_info ^(.+\.php)(/.*)$;
       include fastcgi_params;
       fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
       fastcgi_param DOCUMENT_ROOT $realpath_root;
       internal;
   }
   location ~ \.php$ {
       return 404;
   }
   error_log /var/log/nginx/symfony_error.log;
   access_log /var/log/nginx/symfony_access.log;
}
```

read more here: https://www.howtoforge.com/how-to-setup-symfony-5-framework-on-debian-10/

**Comment by timowevel03** [comment]
Thank you, I will give it a try!

**Comment by timowevel03** [comment]
Works like a charm, thank you really much!

**Comment by timowevel03** [comment]
> Hi !
> I have the same problem,
> Jitsi use nginx by default so it will be really appreciate to have the equivalent configuration.
> 
> Thanks.

See his answer, works like a charm. Thanks @holema !
