### ISSUE TITLE
Add default Jitsi Server with JWT

### ISSUE THREAD

**Issue by timowevel03** [H2-invent/jitsi-admin#198]
Hello,

it would be really nice to be able to predefine a Jitsi Server with configured JWT so every new user can use it.

Is it even possible to set a default server with no JWT configured?

Thanks.

**Comment by holzi1005** [comment]
Hi @timowevel03 
yes you can add a jitsi without jwt and add them as default.
The default has no required jwt.

**Comment by timowevel03** [comment]
Thank you! Could you tell me if I have to add it to the .env.local? Couldnt find anything related to this.
Setting the default JWT ID and Secret, is this something what can come in the future? 

Thanks.

**Comment by timowevel03** [comment]
Setting the Server ID, right. But from where does it take them?

**Comment by timowevel03** [comment]
Found it in the database, thanks.

**Comment by holema** [comment]
@timowevel03 this can be set be add the server Id to the .env.local with 
`default_jitsi_server_id=<yourID>`

**Comment by timowevel03** [comment]
Thanks, already found it. Thank you anyway.

Is it planned to be able to set the JWT credentials in advance in the .env.local? For example I am using Jitsi Admin for my company and we got a server secured with JWT auth to secure it. We dont want to enter the credentials every time and none of my employees should enter the JWT credentials by hand, they should already be configured. Only my employees got access to the Jitsi Admin instance, so it is no issue when JWT is already preconfigured. Any chance to do that?

**Comment by holzi1005** [comment]
HI @timowevel03 
at the moment, that is not possible and for now it is not planed to add this feature soon. 
Then there is a need for this feature, please contact us directly via our website contact form https://h2-invent.com/kontakt and we can see how we can add this feature.

**Comment by timowevel03** [comment]
Thanks for your answer.
I saw that it actually is implemented. By using the server ID with configured JWT it automatically applies it to new created accounts.
