### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by klepptor** [H2-invent/jitsi-admin#200]
**Is your feature request related to a problem? Please describe.**

I'm trying to setup jitsi-admin in our lan environment. As we didn't run a keycloak server before I had to setup this as well and got it running using docker. Unfortunately the documentation of your wonderful tool lacks a lot of information about connecting jitsi-admin and keycloack (or any other possible indentity provider!?) so right now I wasn't able to get it running at all.

**Describe the solution you'd like**
Extend the docs with a howto to setup a test environment.

**Comment by holema** [comment]
Hello @klepptor 
what exactly is the problem you are facing?
you just have to run the install.sh and enter all the informations which are asked there.

To connect the Jitsi Admin to the keycloak you only need to set the keycloak URL into the env, the client ID and the client Secret. Then this connection should work without problems.

You can just contact us via aour contactform so we can help you via telephone
https://h2-invent.com/kontakt

**Comment by klepptor** [comment]
OK, sorry @holema for being quite unprecisly. After opening this issue I had to fight Jira and Confluence problems. 😄

I will try again next week with the latest version using Ubuntu 20.04 and have a deeper look into Keycloak as well.

**Comment by klepptor** [comment]
@holema Thx for your patience!

Today I tried again but I'm stuck at configuring Keycloak or the Keycloak settings in Jitsi Admin correctly.

I used a fresh Ubuntu 20.04 VM to test the setup.

So at first I had to install Apache and PHP with the necessary modules. The docs [here ](https://github.com/H2-invent/jitsi-admin/wiki/Minimum-server-requirements-English) don't tell anything about the details, so I had to guess from the error messages from install.sh

After answering all questions of the script I got this env.local:

==================================

DATABASE_URL=mysql://jitsiadmin:password@dbhost.de:3306/jitsiadmin
DATABSE_SERVER=<mariadb-10.4.6>

###> symfony/framework-bundle ###
APP_ENV=prod
APP_DEBUG=0
APP_SECRET=<app_secret>

###> symfony/swift_mailer ###
MAILER_HOST=mymailserver.de
MAILER_PORT=25
MAILER_PASSWORD=A3sdfsdfdsf
MAILER_USERNAME=username
MAILER_ENCRYPTION=none
MAILER_TRANSPORT=smtp

###ODC Parameters###
imprint=</impressum>
dataPrivacy=</datenschutzhinweis>
helpUrl=</help>

###Cron Parameters###
CRON_TOKEN=<sha256>
CRON_IPADRESS=127.0.0.1

###Emails###
registerEmailName=datenschutz.domain.com
DEV_EMAIL=dev@domain.com
DEFAULT_EMAIL=not@domain.com

TRUSTED_PROXIES=127.0.0.1

###> hwi/oauth-bundle ###
OAUTH_KEYCLOAK_CLIENT_ID=jitsiadmin
OAUTH_KEYCLOAK_CLIENT_SECRET=6c21c201-b940-4c40-b1fa-9e701fa46b47
OAUTH_KEYCLOAK_SERVER=keycloak.myserver.de/auth
OAUTH_KEYCLOAK_REALM=myrealm
###< hwi/oauth-bundle ###

###> demo ###
demo_installation=prod
###< demo ###

###> matomo ###
matomo_enable=false
matomo_id=1
matomo_url=analytics.local.com
###< matomo ###

###> LaF ###
laF_bbb=0
laF_startpage=false
laF_onlyRegisteredParticipents=0
laF_version=2.0.0-dev
laF_pexel_api_key=#EnterAPIKeyHere
laF_pexel_refresh_time=1200
laF_baseUrl=jitsiadmin.myserver.de
laF_emailTextLogin=1
laf_CreateServerOpenToEveryone=1
laf_keycloakGroupToCreateServer=/user
laf_administratorEmail=admin@localhost.de
laf_notificationUrl=""
laf_bbb_Url=""
laf_max_repeat=56
###< LaF ###

###> Default Jitsi Server ###
default_jitsi_server_id=0
###< Default Jitsi Server ###

### Enterprise Settings ###
enterprise_noExternal=0
###<Enterprise Settings>###

==================================

I'm using this Apache Config:

==================================
<VirtualHost *:80>

    ServerAdmin mail@myserver.de

    ServerName jitsiadmin.myserver.de

'#    Redirect permanent / https://jitsiadmin.myserver.de
</VirtualHost>

<VirtualHost *:443>

    ServerName jitsiadmin.myserver.de

    Protocols h2 http/1.1

    SSLEngine on
    SSLCertificateFile "/etc/ssl/private/cert.crt"
    SSLCertificateKeyFile "/etc/ssl/private/cert.key"

    DocumentRoot /var/www/jitsi-admin/public/

    <Directory /var/www/jitsi-admin/public>
            Options FollowSymLinks
            AllowOverride All
            Order Allow,Deny
            Allow from All
    </Directory>

    ErrorLog ${APACHE_LOG_DIR}/error_jitsi-admin.log
    CustomLog ${APACHE_LOG_DIR}/access_jitsi-admin.log combined
</VirtualHost>
==================================

Keycloak Client looks like this (here I'm quit unsure about the settings):

![image](https://user-images.githubusercontent.com/3921511/121685919-d15d0d00-cac0-11eb-8020-bc912e56f3ff.png)

![image](https://user-images.githubusercontent.com/3921511/121686077-036e6f00-cac1-11eb-8966-8838a79235a2.png)
![image](https://user-images.githubusercontent.com/3921511/121686112-0cf7d700-cac1-11eb-82d1-e9837ea4bbda.png)

And that's the result when opening the server address...

![image](https://user-images.githubusercontent.com/3921511/121686307-49c3ce00-cac1-11eb-88f1-9ab08a824094.png)

The Apache error log is empty

**Comment by holema** [comment]
hello @klepptor,
can you post the log file from Symfony? this can be found at /var/log/prog.log. With this I can look whats wrong.

**Comment by klepptor** [comment]
Hi @holema 

with your hint to the logs I got it working, at least most of the functionality.

But I noticed several ways to mess up the installation using install.sh.

1. it's quite unclear how to write the address of the Keycloak Server (with/without http(s)), an example in install.sh would be nice
    if using https it throwing a sed error and not changing <keycloak> to the given url, changing it in .env.local manually works fine
    
2. swift mailer config cannot be used without encryption although the docs [here](https://symfony.com/doc/current/reference/configuration/swiftmailer.html#encryption) tell to use the "null" encryption (I think install.sh asks about "none" encryption!?), both config options lead to ("null" or "none":
![image](https://user-images.githubusercontent.com/3921511/122534058-74160e00-d022-11eb-8caf-3eb9d6111bff.png)

3. install.sh doesn't check the correct file/dir permission, I noticed while looking for prod.log, which had the ownership of the user I used to clone the repo, not www-data. Is BranchPipeline.sh needed here? Didn't work...

All these item are single issues from my point of view that should be solved and/or documented for your wonderful tool to become more easily installable on premises! I think the best way would be a docker image with all dependencies exporting only an unencrypted http port, so you can easily use it with a (existing) reverse proxy, updating would be even more easy and no more trouble like I had at all (except the mailer).

At least my problems about getting startet at all are solved now. Next I will try to setup the permissions for the users in Keycloak about setting up server etc using your existing docs.

**Comment by AlexanderGabriel** [comment]
This is closed but i have some information for you:
install tool got updated in open-event-manager. if i have time the next days, i will look if i can use the patch from here for jitsi admin https://github.com/open-event-manager/open-event-manager/pull/13
When doing this i can add a hint for keycloak-url. i was not so happy with the install tool aswell ;)

no idea how to easily check installed php modules from command line but working on a ansible playbook to install dependencies for open-event-manager and jitsi-admin because in run in errors every time, too.

i think it is good, not to change ownership of files to www-data  by install.sh. if you use some software like plesk oder iscpconfig to manager your server of use AssignUserID in apache to permission-seperate different websites, the user is not www-data any more and you will run in erros. other software does not check this, too and the installing person has to look for this. annoying. i know.

**Comment by AlexanderGabriel** [comment]
Update install tool PR: https://github.com/H2-invent/jitsi-admin/pull/210
