### ISSUE TITLE
Just show 404

### ISSUE THREAD

**Issue by gcommit** [H2-invent/jitsi-admin#207]
I downloaded your repo here. I then run `docker-compose up --build` and tried to call the Webinterface, which resulted in 404

Then i loged into the container, installed mariadb, created a user and a database and ran the install.sh

Called the Webinterface -> 404

I am calling it with `http://localhost`

What am i doing wrong?

**Comment by gcommit** [comment]
i got this. It is redirecting me after installation to /room/dashboard , which leads to a 404 again.

any help?

**Comment by holema** [comment]
you need to install keycloak as a sso provider.

**Comment by holema** [comment]
hello @gcommit,
did it work now? Or do you need any more help?

**Comment by gcommit** [comment]
i did install keycloak, but i get always a "invalid redirect uri"
$PUBLIC_IP is a placeholder so i don't publish my IP here...

.env.local:
OAUTH_KEYCLOAK_CLIENT_ID=Jitsi
OAUTH_KEYCLOAK_CLIENT_SECRET=39acd12a-c5b8-4950-a947-b6ca30a4250a
OAUTH_KEYCLOAK_SERVER=http://$PUBLIC_IP:8080/auth
OAUTH_KEYCLOAK_REALM=master


Keycloak:
(screenshot)
<img width="762" alt="Bildschirmfoto 2021-06-22 um 16 07 25" src="https://user-images.githubusercontent.com/18714033/122939541-00eaff80-d374-11eb-90fc-2876153f83fd.png">


Keycloak is running on 0.0.0.0:8080 and apache2 on 0.0.0.0:80

I don't understand where my error is, since in your wiki you just say "Create a new client"

**Comment by AlexanderGabriel** [comment]
base url is the url of the jitsiadmin, not keycloak. admin url same

**Comment by AlexanderGabriel** [comment]
this is how it looks here:
![image](https://user-images.githubusercontent.com/23343388/122941081-583d9f80-d375-11eb-96de-6ead067ced33.png)

**Comment by gcommit** [comment]
I configured it now this way, it is still redirecting to: http://$PUBLIC_IP:8080/auth/realms/master/protocol/openid-connect/auth?scope=email&state=67d31bb760890d9eb00e5b235a20d899&response_type=code&approval_prompt=auto&redirect_uri=https%3A%2F%2F193.142.157.159%2Flogin%2Fkeycloak_login%2Fcheck&client_id=Jitsi

<img width="759" alt="Bildschirmfoto 2021-06-22 um 16 20 02" src="https://user-images.githubusercontent.com/18714033/122941468-b5d1ec00-d375-11eb-8989-699641589bd7.png">

**Comment by AlexanderGabriel** [comment]
try that happens if you change [https] to [http] in config/routes/prod/keycloak.yml

@holema i have simmilar problems when working in dev-env but the route changes protocol to http even if i have https active in my dev-environment.

**Comment by AlexanderGabriel** [comment]
btw: your ip is still visible in the url above. if you want to keep it secret, change your post...

**Comment by gcommit** [comment]
@AlexanderGabriel thanks, i changed the post

i changed https to http in keycloak.yml and restarted apache2 - still happens. 

Is there any documentation i can follow? The wiki documentation (https://github.com/H2-invent/jitsi-admin/wiki) is not usefull/helpfull for someone who did not work with keycloak so far

**Comment by AlexanderGabriel** [comment]
maybe you need to clear cache on server-side...
open console in the jitsiadmin-webroot and execute "php bin/console cache:clear"

i dont think, this problem is covered by documentation. they expect that you use https in production. what happens if you change "prod" to "dev" in your .env.local? just to see if this is the screw we need to turn ;)

**Comment by gcommit** [comment]
"php bin/console cache:clear" did something. It kinda works now, but now after login, i get this

<img width="358" alt="Bildschirmfoto 2021-06-22 um 17 48 56" src="https://user-images.githubusercontent.com/18714033/122957351-24b54200-d382-11eb-82d2-0d7475f6e751.png">

**Comment by gcommit** [comment]
```
=> /var/log/apache2/access.log <==
93.195.76.49 - - [22/Jun/2021:16:00:49 +0000] "GET /login/keycloak_login/check?state=6090f60577147540acab52b64eb8987b&session_state=34bf9549-c54d-429e-930b-16821a3afa13&code=cdfd3380-d0cf-4d01-99a3-e95f8c66cba2.34bf9549-c54d-429e-930b-16821a3afa13.d0379776-c9c9-4c41-ab2f-6d8c58875de3 HTTP/1.1" 302 563 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
93.195.76.49 - - [22/Jun/2021:16:00:49 +0000] "GET / HTTP/1.1" 302 632 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
93.195.76.49 - - [22/Jun/2021:16:00:49 +0000] "GET /room/dashboard HTTP/1.1" 302 587 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
93.195.76.49 - - [22/Jun/2021:16:00:49 +0000] "GET /login HTTP/1.1" 302 1923 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
93.195.76.49 - - [22/Jun/2021:16:00:49 +0000] "GET /login/keycloak_login/check?state=c16e22b858bb794765d613b30a74c650&session_state=34bf9549-c54d-429e-930b-16821a3afa13&code=64da10f2-6c6d-4dab-8a0d-37429a5fddf1.34bf9549-c54d-429e-930b-16821a3afa13.d0379776-c9c9-4c41-ab2f-6d8c58875de3 HTTP/1.1" 500 1018 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15"
```

**Comment by AlexanderGabriel** [comment]
there is a logfile in subfolder var/log which should show better error message.
the var/log folder needs write permission for the user of the webserver (most times www-data)

**Comment by gcommit** [comment]
Which logs do you mean? This is all i got when i do a "tail -f /var/log/apache2/*"

**Comment by gcommit** [comment]
It now says: 

```[2021-06-23T11:51:39.198853+00:00] request.CRITICAL: Uncaught PHP Exception Twig\Error\RuntimeError: "An exception has been thrown during the rendering of a template ("Cannot parse message translation: please install the "intl" PHP extension or the "symfony/polyfill-intl-messageformatter" package.")." at /var/www/html/templates/base/__topnav.html.twig line 6 {"exception":"[object] (Twig\\Error\\RuntimeError(code: 0): An exception has been thrown during the rendering of a template (\"Cannot parse message translation: please install the \"intl\" PHP extension or the \"symfony/polyfill-intl-messageformatter\" package.\"). at /var/www/html/templates/base/__topnav.html.twig:6)\n[previous exception] [object] (Symfony\\Component\\Translation\\Exception\\LogicException(code: 0): Cannot parse message translation: please install the \"intl\" PHP extension or the \"symfony/polyfill-intl-messageformatter\" package. at /var/www/html/vendor/symfony/translation/Formatter/IntlFormatter.php:38)"} []```

I installed php7.2-intl but it still shows this error

**Comment by gcommit** [comment]
I got it!

`curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer && composer require symfony/polyfill-intl-messageformatter`

**Comment by holema** [comment]
Hello @gcommit,
You need for the latest version php7.4.
For rendereing the template you need to install the php-intl extension. This is necessary to render the date and time on the dashboard.

**Comment by holema** [comment]
@gcommit the error with the 

> ```
> [2021-06-23T07:13:07.567650+00:00] request.INFO: Matched route "connect_keycloak_check". {"route":"connect_keycloak_check","route_parameters":{"_route":"connect_keycloak_check","_controller":"App\\Controller\\LoginControllerKeycloak::check","_locale":"de"},"request_uri":"http://193.142.157.159/login/keycloak_login/check?code=c97a1c18-b1b0-42bd-9c58-dd57a865f8e7.02785f8b-bab7-49f1-bbbd-7bf3cb1669d2.d0379776-c9c9-4c41-ab2f-6d8c58875de3&session_state=02785f8b-bab7-49f1-bbbd-7bf3cb1669d2&state=410009d38089d01e2135879890a7a622","method":"GET"} []
> [2021-06-23T07:13:07.568728+00:00] security.DEBUG: Checking for guard authentication credentials. {"firewall_key":"main","authenticators":1} []
> [2021-06-23T07:13:07.568739+00:00] security.DEBUG: Checking support on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\GuardServiceKeycloak"} []
> [2021-06-23T07:13:07.568751+00:00] security.DEBUG: Calling getCredentials() on guard authenticator. {"firewall_key":"main","authenticator":"App\\Security\\GuardServiceKeycloak"} []
> [2021-06-23T07:13:07.579039+00:00] security.DEBUG: Passing guard token information to the GuardAuthenticationProvider {"firewall_key":"main","authenticator":"App\\Security\\GuardServiceKeycloak"} []
> [2021-06-23T07:13:07.583242+00:00] php.WARNING: Notice: Undefined index: email {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: email at /var/www/html/vendor/stevenmaguire/oauth2-keycloak/src/Provider/KeycloakResourceOwner.php:43)"} []
> [2021-06-23T07:13:07.583282+00:00] php.WARNING: Notice: Undefined index: given_name {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: given_name at /var/www/html/src/Security/GuardServiceKeycloak.php:60)"} []
> [2021-06-23T07:13:07.583302+00:00] php.WARNING: Notice: Undefined index: family_name {"exception":"[object] (ErrorException(code: 0): Notice: Undefined index: family_name at /var/www/html/src/Security/GuardServiceKeycloak.php:61)"} []
> [2021-06-23T07:13:07.590197+00:00] php.CRITICAL: Uncaught Error: Argument 1 passed to App\Entity\UserBase::setUuid() must be of the type string, null given, called in /var/www/html/src/Security/GuardServiceKeycloak.php on line 101 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Entity\\UserBase::setUuid() must be of the type string, null given, called in /var/www/html/src/Security/GuardServiceKeycloak.php on line 101 at /var/www/html/src/Entity/UserBase.php:39)"} []
> [2021-06-23T07:13:07.592087+00:00] request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 1 passed to App\Entity\UserBase::setUuid() must be of the type string, null given, called in /var/www/html/src/Security/GuardServiceKeycloak.php on line 101" at /var/www/html/src/Entity/UserBase.php line 39 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to App\\Entity\\UserBase::setUuid() must be of the type string, null given, called in /var/www/html/src/Security/GuardServiceKeycloak.php on line 101 at /var/www/html/src/Entity/UserBase.php:39)"} []
> ```

Comes because your jitsi-admin is in prod environment. this leads to the situation, that the jitsiadmin automaticaly adds a https and not a http to the guard route.
if you local dev-environment is not HTTPS ready, then remove the line ```   schemes:    [https] ``` in the file
**config>routes>prod>keycloak.yml**

**Comment by gcommit** [comment]
This fixed it:

`curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer && sudo -u www-data composer require symfony/polyfill-intl-messageformatter`

**Comment by holema** [comment]
hello @gcommit,
this is a strange behaviour, because in all our installation, just 5min ago, the symfony/polyfill-intl-messageformatter package is installed by default.
But I`m happy that is is now working as expected.
