### ISSUE TITLE
"Ready" mail when all participants answered a schedule

### ISSUE THREAD

**Issue by klepptor** [H2-invent/jitsi-admin#212]
**Is your feature request related to a problem? Please describe.**

Right now the creator of a schedule isn't informed when all participants answered, so you have to check manually.

**Describe the solution you'd like**

After all participants answered a email is sent to the creator of the schedule and tells him that the schedule is ready to make the appointment.
Additionally an icon in the dashboard should inform about the status of the schedule.

![image](https://user-images.githubusercontent.com/3921511/122927134-dcd5f100-d368-11eb-80c5-b1a65cdd08fa.png)

**Describe alternatives you've considered**
Manually check the answers...

**Comment by holema** [comment]
Hello @klepptor,
this is an interesting Feature Request.
Can you write us directly via our webseite, so we can write there more about it.
https://h2-invent.com/kontakt
Best regards
Emanuel Holzmann

**Comment by holema** [comment]
This feature will be implemented in version 0.76 which is in development actually
