### ISSUE TITLE
Update Documentation

### ISSUE THREAD

**Issue by AlexanderGabriel** [H2-invent/jitsi-admin#215]
Es wird nirgends erwähnt, dass man NodeJS und PHP mit verschiedenen Modulen installieren muss.
Wäre super, wenn das aus der Installationsanleitung noch hervor geht, weil das Install-Tool die ganzen Sachen nämlich nicht prüft:
      - npm
      - nodejs
      - php7.4
      - php7.4-mbstring
      - php7.4-xsl
      - php7.4-dom
      - php7.4-xml
      - php7.4-gd
      - php7.4-zip
      - php7.4-intl
      - php7.4-curl
      - php7.4-mysql
      - apache2
      - libapache2-mod-php7.4
      - composer

**Comment by klepptor** [comment]
Bin ganz bei Dir, die Doku ist noch sehr rudimentär. ;)

S. auch hier: https://github.com/H2-invent/jitsi-admin/issues/200

**Comment by AlexanderGabriel** [comment]
Hängt halt immer vom Niveau ab. Ich komm da schon durch, die Installation bei uns haben wir trotzdem von H2-Invent machen lassen, als ich gemerkt hab, dass man da noch Keycloak braucht.
Hat sich unterm Strich gelohnt. Jetzt kann ich das selbst aber wie man Keycloak aufsetzt wird ja nie in die Doku eines Clients gehören.
Dafür ist die Onlinehilfe für die Anwender relativ gut.

BTW: Das Install-Tool ist jetzt nen ticken besser. Hab demnächst Urlaub, wenn ich Langeweile hab schau ich mal, wie man mit der Bash prüfen kann, welche PHP-Version, Module, etc. installiert sind.

**Comment by holema** [comment]
@AlexanderGabriel: Das werde ich noch in die Doku aufnehmen.
Das ist richtig, das wir die Installationsduko noch etwas verbessern müssen und das auch noch machen.

**Comment by AlexanderGabriel** [comment]
Stellt die Doku doch einfach irgendwo hin, sodass User diese aktualisieren können. Als install.md oder so hier rein. Geht das nicht?

Mach dann hier zu, ist ja erledigt.
