### ISSUE TITLE
Word used for "Serienvideokonferenz"

### ISSUE THREAD

**Issue by AlexanderGabriel** [H2-invent/jitsi-admin#223]
Eigentlich eine Frage, damit ich mir nicht unnötig Arbeit mache.
Die Englische Übersetzung für Serienvideokonferenz ist aktuell seriesvideoconfence, obwohl ich mir sicher bin, dass es das Wort im englischen gar nicht gibt.
Ich hätte deshalb gerne vorgeschlagen, zukünftig "repeating videoconference" zu verwenden.
Was haltet ihr davon?

Da sind noch viele Strings zu übersetzen, ich könnte mir die anderen aber auch holen und das gerade ziehen. Natürlich nur, wenn niemand einen besseren Vorschlag hat.

**Comment by holema** [comment]
@AlexanderGabriel Finde ich einen guten und Pragmatischen Ansatz :)
