### ISSUE TITLE
Installation Guide

### ISSUE THREAD

**Issue by SpiderChat** [H2-invent/jitsi-admin#238]
Dear Team

Any installation guide?

**Comment by h2Entwicklung** [comment]
Hello @SpiderChat,

here is the instruction:
https://github.com/H2-invent/jitsi-admin/wiki/Get-Started-English

**Comment by h2Entwicklung** [comment]
on a linux machine, you can just run
`bash install.sh`
after cloning

**Comment by SpiderChat** [comment]
How to get this information:

Enter the base url of the Jitsi-Admin:
Enter the URL to keycloak with /auth at the end:
Keycloak realm:
Keycloak Client Id:
Keycloak Client Secret:

**Comment by h2Entwicklung** [comment]
Hello @SpiderChat,

The Jitsi-Adin uses the keycloak Identityprovider to Sign in.
This is an FOSS Single Sign On System, which has to be installed.
https://www.keycloak.org

In this app you can create a new Client and this values has to bes set there.

**Comment by SpiderChat** [comment]
Using nginx or apache2?

**Comment by SpiderChat** [comment]
Keycloak has been installed on my server.

How to create?
Keycloak realm:
Keycloak Client Id:
Keycloak Client Secret:

**Comment by h2Entwicklung** [comment]
hello @SpiderChat 

We use only apache2 for our Jitsi-Admin.

To create a Realm and a client you have to follow these guidlines
https://www.keycloak.org/docs/latest/getting_started/
https://wjw465150.gitbooks.io/keycloak-documentation/content/authorization_services/topics/resource-server/create-client.html

Best regards

**Comment by h2Entwicklung** [comment]
@SpiderChat 
Is your issue solved?

**Comment by SpiderChat** [comment]
https://www.keycloak.org/getting-started

I have install Keycloak on OpenJDK
Right?

**Comment by h2Entwicklung** [comment]
@SpiderChat 
correct,
and then just start with the command.

**Comment by SpiderChat** [comment]
I was a bit confused about the database.  What is the database used, mysql, mariadb or postgersql?  I just want to make sure before install

**Comment by h2Entwicklung** [comment]
@SpiderChat you mean in the keycloak app? there is an internal h2 database used. But when you want to use it in production I recommend to use mySQL.

**Comment by SpiderChat** [comment]
Can you give me an example for this?

Keycloak realm:
Keycloak Client Id:
Keycloak Client Secret:

Thank you.

**Comment by AlexanderGabriel** [comment]
Keycloak realm is the realm you add when installing keycloak via https://www.keycloak.org/docs/latest/getting_started/ in section https://www.keycloak.org/docs/latest/getting_started/#creating-a-realm-and-a-user. you can choose a string like your company name or something.
Client ID is a free string you enter when configuring client application in keycloak. i chose jitsiadmin here ;) it's this section in the getting started guide: https://www.keycloak.org/docs/latest/getting_started/#registering-the-wildfly-application
Client Secret is a generated GUID you can see after adding the client to keyclok unter "credentials":
![image](https://user-images.githubusercontent.com/23343388/131246926-37fea796-9e46-493e-a808-085df6629b6b.png)

Hope it helps

**Comment by holema** [comment]
Hello @SpiderChat,
Since the last version we have a docker version for the jitsiadmin.
The docker Installation already includes everything  like keycloak, the new Mercure hub, async services and a database.
The installation instructions can be found here.
https://github.com/H2-invent/jitsi-admin/wiki/Install-jitsi-admin-in-docker

So this is much easier to deploy the complete jitsiadmin stack.

**Comment by 297297sid** [comment]
pls help me after cloning code and running bash ,also setting up keycloak client id,realm,password ,when opening base url of jitsiadmin which i provide during installation i am getting 500 internal server eroor how to fix it, also while setting keycloak we have to make realm, client  nd obtain its secreat . Do we also have to setup user in keycloak ?

**Comment by holema** [comment]
This is fixed in the latest version
