### ISSUE TITLE
Configure the email invitation to personal needs 

### ISSUE THREAD

**Issue by MoniYogi** [H2-invent/jitsi-admin#239]
**Is your feature request related to a problem? Please describe.**
No- it is a feature request.

**Describe the solution you'd like**
When I invite participants to a meeting that I am setting up in Jitsi Admin, the email sent to the participants always has the same subject and the sender is „Jitsi Manager“. The details of the conference are in the body. This makes it difficult for a participant  who wants to join a meeting to find the related email in his/her inbox. It would be nice to have the meeting title in the subject line as well as date and time. In addition, it would be great, if the sender could be the person who is setting up the conference instead of „Jitsi Manager“.

**Describe alternatives you've considered**
a really super-comfortable solution could foresee that the email can be configured by the user.

**Additional context**

**Comment by h2Entwicklung** [comment]
@MoniYogi 
The Ideas are good, and I will look that I add there features to a furture version.

**Comment by holema** [comment]
closed because of inactivity
