### ISSUE TITLE
JWT Konfiguration

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#241]
Hallo,

ich habe JWT installiert, wie hier beschrieben: https://github.com/jitsi/lib-jitsi-meet/blob/master/doc/tokens.md#installing-token-plugin

Kommt eine Nutzer*in eine Stunde zu früh, erscheint ein Hinweis, dass alles man erst 30 Minuten vorher eintreten kann. OK.
Wenn aber ein Nutzer dann vor mir (ich bin im Jitsi-Admin als Moderator oder Organisator eingetragen) kommt, hat er oder sie die Moderationsrechte.

Muss ich da etwas anders einstellen oder ist das so?

Viele Grüße

Daniel

**Comment by xdaniel2063** [comment]
Hallo,
ja, die JWT Credentials sind eingetragen.

Greift jemand ohne Token auf einen der Räume zu, kommt er/sie auch nicht weiter. Funktioniert also.

Die Generierung des Tokens durch den Jitsi-Admin und die Weitergabe an den Jitsi-Server funktioniert auch. Die Nutzer können den Raum mit dem Token des Jitsi-Admin erstellen. 

Aber eben auch die, die nicht als Moderation eingetragen sind.  Es wird der/die Moderator/in, die zuerst da ist. Sowie das Jitsi-Prinzip im Rohzustand eben ist.

**Comment by holzi1005** [comment]
Es muss noch ein Prosody Plugin installiert werden damit die Funktion des Moderators verwendet werden kann.
https://github.com/nvonahsen/jitsi-token-moderation-plugin

**Comment by xdaniel2063** [comment]
Hallo Andreas, ja, das war es nun funktioniert es. Vielen Dank.
