### ISSUE TITLE
jitsdi-admin.de

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#242]
Hallo,
in der Vergangenheit hat der jitsi-admin.de immer kurz vor der Konferenz Erinnerungen abgeschickt. Das war ein nützlicher Service. Ist die Funktion nicht mehr da oder muss ich irgendwo gesondert Häkchen setzen?
Viele Grüße
Daniel

**Comment by h2Entwicklung** [comment]
Hallo @xdaniel2063,

Vielen Dank für die Hinweis.
Die Funktion sollte eigentlich noch weiterhin da sein.
Kannst du mal nachschauen, ob in deinem Browser Push-Notifications erlaubt sind?

VG

**Comment by xdaniel2063** [comment]
Ich meinte aber die Erinnerungs-E-Mails? Benachrichtigungen senden ist erlaubt...
