### ISSUE TITLE
Language Bug

### ISSUE THREAD

**Issue by jasonjenssen** [H2-invent/jitsi-admin#247]
Hello,

I changed the default language in config/packages/jms_i18n_routing.yaml

But the page when you open an invite link is still German. Is this a bug?

![image](https://user-images.githubusercontent.com/25285295/134426998-0078a230-3224-46cf-8d09-94bec9ded899.png)

**Comment by jasonjenssen** [comment]
Hey, any ideas?

**Comment by obelisk-services** [comment]
Hi,

I think you have to change it there and in config/packages/translation.yaml

Hope this helps.
Best regards
