### ISSUE TITLE
Teilnehmende in Warteliste verschieben

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#250]
Hallo,

ist es möglich einen Teilnehmer auf die Warteliste zu setzen, bevor die Teilnehmerzahl erreicht ist?

Ich kündige demnächst fünf Web-Seminare (ähnliche aber nicht gleiche Inhalte) an. Möchte aber aufgrund der begrenzten TN-Zahl von 25, dass die Leute sich nicht gleich für alle fünf anmelden können. Das geht ja nicht. 

Nun gibt es aber schlaue Leute,  die genau das tun und dann nicht kommen. Ich würde diese gerne erstmal auf die Warteliste setzen (verschieben) und nur zulassen, wenn z.B. einen Tag vorher noch Plätze frei sind?

Viele Grüße

Daniel

**Comment by h2Entwicklung** [comment]
Hallo @xdaniel2063 
Das geht leider noch nicht.
dafür müssten wir dann den Workflow anpassen.
Das klingt nach einem guten Feature Request und ich schaue mal wann ich das einbauen kann.

Viele Grüße

**Comment by holema** [comment]
closed because of inactivity
