### ISSUE TITLE
Can't add new participants

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#264]
Hello,
while trying to add new participants I got a "null" instead of the emailadress (jitsi-admin.de).
[Screenshot](https://mybins.meet21.de/?9b20812e18fb15de#Ft5XSt5vWtFTBzG1Y9P8j9yTiNwfJE26X7cCcYGDbuvX)
Best, Daniel

**Comment by xdaniel2063** [comment]
[the screenshot / error after sending.](https://mybins.meet21.de/?33c434876b3db214#Hi2M8wXrR57H6RyNee73Q943vdf6PoUuPRBcy5n1rAE1)

**Comment by holema** [comment]
Hello @xdaniel2063 
can you tell us what you have typed in the search box?

**Comment by xdaniel2063** [comment]
had the same problem yesterday again. I search for an email. If the user already exists and I click to add him, the jitsi-admin adds "null". It happens not with all emails.

**Comment by holema** [comment]
@xdaniel2063 
I wrote you an email to find the issue. BEcause I need some deeper information about the email. We will post the solution here.

**Comment by holema** [comment]
Hello @xdaniel2063,
thanks for writing the bug.
We fixed the issue and now you can add the user.

**Comment by holema** [comment]
@xdaniel2063,
can you confirm that searching email adresses are working now? then I can close this issue.

**Comment by xdaniel2063** [comment]
Yes it works, thanks a lot!
