### ISSUE TITLE
Moderator

### ISSUE THREAD

**Issue by RoundAboutWEB** [H2-invent/jitsi-admin#268]
Alle Teilnehmer per Link sind Moderatoren und können somit alle Einstellungen in einer Konferenz verändern. Es sollte aber nur einen Moderator geben, der ggf. weitere zu Moderatoren erklärt. Zu funktionieren scheint es nur, wenn man nur definierte Teilnehmer einläd und diese vorab zum Moderator macht oder eben nicht. Doch jeder der per Link teilnimmt ist automatisch Moderator - warum, bzw. was mache ich falsch?

**Comment by holema** [comment]
Hallo @RoundAboutWEB,
Welchen Link haben Sie an die Teilnehmer geschickt?
Haben sie den Link aus Ihrer Email an die Teilnehmer weitergeleitet?
Oder haben Sie eine Konferenz ohne Teilnehmerliste erstellt.
Sie können mir den Link gerne per E-Mail an entwicklung@h2-invent.com senden, dann kann ich mir den JWT-Token ansehen.

Viele Grüße

**Comment by RoundAboutWEB** [comment]
Hallo @holema, 

Danke für die schnelle Rückmeldung. Es handelt sich hier noch um eine Testkonferenz, daher füge ich hier gleich den Link bei, da diese Konferenz nach dem Test eh gelöscht wird.

Die Teilnahme wird ohne Teilnehmerliste erfolgen über folgenden Link:
https://jitsi-admin.de/myRoom/start/741641291557

Wer sich über diesen Link als Teilnehmer anmeldet hat jedoch Moderationsrechte (Sicherheitsoptionen, ...).

**Comment by xdaniel2063** [comment]
@RoundAboutWEB Ich denke, dass ist das normale Verhalten, da Du den 8x8 Server verwendest. Auf Deinem eigenen Server könntest Du durch die JWT-Authentifizierung die entsprechenden Rollen vergeben.

**Comment by RoundAboutWEB** [comment]
Es ist bei Jitsi "normal", dass jeder Teilnehmer volle Rechte hat? Man benötigt also Rollen um Rechte einzuschränken? Das würde natürlich einiges erklären, aber wie werden Teilnehmer dann mit der eingeschränkten Rolle verknüpft, wenn sie sich nur über einen Link und ohne Profil anmelden? Normalerweise kenne ich es von anderen Portalen so, dass der Moderator die Sitzung eröffnet und alle Teilnehmer erst mal keine Rechte haben, es sei denn der Moderator bestimmt weitere Moderatoren.

**Comment by xdaniel2063** [comment]
Ja, das funktioniert über den mit der URL vergebenen Token. Die Keys werden aber bei dem öffentlichen Server unter meet.jit.si wahrscheinlich nicht öffentlich sein. Dort hat man über https://moderated.jitsi.net/ die Möglichkeit gesicherte Moderatoren-Rechte zu bekommen.

Kannst mir ja mal eine E-Mail senden, dann kannst Du Dir das auf meinem Server https://meet-lev.de mal über den Jitsi-Admin ansehen.

**Comment by holema** [comment]
Hallo @RoundAboutWEB,
das ist das normal verhalten bei einem JItsi-Server.
Die Berechtigungen werden über JWT vergeben. Dies ist ein Token welcher signiert ist.
Hierfür muss aber der Jitsi-Server mit einer Erweiterung ausgestattet sein. Erst dann kann der Jitsi-Server den JWT, welcher vom Jitsi-Admin generiert wird auslesen und den Benutzern die einzelnen Rechte geben.
Der Standardserver von Jitsi ist nicht mit einer JWT Absicherung betrieben, weswegen es hier nicht funktioniert.

Viele Grüße
