### ISSUE TITLE
ICS-Datei ohne Endung

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#269]
Hallo,

heute hat der Server die den Einladungen anhänge Datei wieder ohne Endung versendet (.ics fehlt).
Siehe Screenshot: https://mybins.meet21.de/?daa793dee10e282b#BG2JSSRs2QPzssg62aKRbthbh8o4mgCinoeDDXLyjggC

Viele Grüße

Daniel

**Comment by h2Entwicklung** [comment]
Hallo @xdaniel2063,

Ich habe gerade probiert eine Konferenz zu erstellen und bei mir war die ics komplett vorhanden, incl. der Endung.
Kannst du mir vllt. mal die Einladung an entwicklung@h2-invent.com weiterleiten.
Hast du die Konferenz auf der originalen Jitsi-Admin Seite erstellt, oder habt ihr eine eigene Jitsi-Admin instanz?

Viele Grüße

**Comment by xdaniel2063** [comment]
Habe ich geschickt.

**Comment by holema** [comment]
@xdaniel2063 ich würde dieses Ticket schleißen. Irgendwie muss es ja an deinem Mailprogramm gelegen haben.
Ist es noch möglich das dein Outlook den Dateinamen abgeschnitten hat, auf den sichtbaren Bereich, der dir bei der Email-Anzeige angezeigt wird?

**Comment by xdaniel2063** [comment]
ok, ich behalte es im Auge. Wie geschrieben, es ist Standard-Outlook 365 und sowohl in der App als auch in der Webversion. Es taucht ja nur in wenigen Fällen auf. Ich schließe es dann.
