### ISSUE TITLE
Create meeting room right via keycloak group

### ISSUE THREAD

**Issue by bienxanh1901** [H2-invent/jitsi-admin#273]
Hello,
I am very interesting with this jitsi-admin. It is very useful for me to create meeting room and specify the moderator.
My question is that: can we limit the users that can create meeting room via keycloak group?
For example: only user in group teachers can create meeting room

Thank you very much!

**Comment by h2Entwicklung** [comment]
Hello @bienxanh1901,
do you operate your own jitsi-admin?
If so, you can add the users in keycloakgroups and connect the jitsi server with the groups.

This is the instruction you are looking for. :)
https://github.com/H2-invent/jitsi-admin/wiki/Organize-Jitsi-Servers-via-keycloak-groups
