### ISSUE TITLE
Cannot autowire service "App\Command\AddSlugToServerCommand"

### ISSUE THREAD

**Issue by Sherif-khaled** [H2-invent/jitsi-admin#281]
Hello,
After installed jitsi admin and configur it to keycloak,and when login to admin panel i get 500 error,

when i open debug i get this error

<code>Cannot autowire service "App\Command\AddSlugToServerCommand": argument "$name" of method "__construct()" is type-hinted "string", you should configure its value explicitly.</code>

<pre><code>
DATABASE_URL=mysql://testuser:16121987@localhost:3306/jitsi
DATABSE_SERVER=<mariadb-10.4.6>

###> symfony/framework-bundle ###
APP_ENV=prod
APP_DEBUG=1
APP_SECRET=base64:GPL81umP/IVo1uss9Z9INNw45+HysQWzqGbZeT+xDNw=

###> symfony/swift_mailer ###
MAILER_HOST=
MAILER_PORT=
MAILER_PASSWORD=
MAILER_USERNAME=
MAILER_ENCRYPTION=
MAILER_TRANSPORT=

###ODC Parameters###
imprint=</impressum>
dataPrivacy=</datenschutzhinweis>
helpUrl=</help>

###Cron Parameters###
CRON_TOKEN=<sha256>
CRON_IPADRESS=127.0.0.1

###Emails###
registerEmailName=datenschutz.domain.com
DEV_EMAIL=dev@domain.com
DEFAULT_EMAIL=not@domain.com

TRUSTED_PROXIES=127.0.0.1

###> hwi/oauth-bundle ###
OAUTH_KEYCLOAK_CLIENT_ID=jitsi_admin
OAUTH_KEYCLOAK_CLIENT_SECRET=ieDZA5oGZp6tme7vfq5YMJ7GN0RUDnkI
OAUTH_KEYCLOAK_SERVER=http://110.218.124.113:8180/auth
OAUTH_KEYCLOAK_REALM=jitsiadmin

###< hwi/oauth-bundle ###

###> demo ###
demo_installation=prod
###< demo ###

###> matomo ###
matomo_enable=false
matomo_id=1
matomo_url=analytics.local.com
###< matomo ###

###> LaF ###
laF_bbb=0
laF_startpage=false
laF_onlyRegisteredParticipents=0
laF_version=2.0.0-dev
laF_pexel_api_key=#EnterAPIKeyHere
laF_pexel_refresh_time=1200
laF_baseUrl=<baseUrl>
laF_emailTextLogin=1
laf_CreateServerOpenToEveryone=1
laf_keycloakGroupToCreateServer=/user
laf_administratorEmail=admin@localhost.de
laf_notificationUrl=""
laf_bbb_Url=""
laf_max_repeat=56
laf_refreshTimeDashboard=10000
laf_darkmodeAsDefault=0
laf_showName="user.username$"
laf_showNameFrontend="user.firstName$ user.lastName$"
laf_addParticipantsNoInput=0
laf_roomsMoreOptionsCollapsed=1
###< LaF ###

###> Default Jitsi Server ###
default_jitsi_server_id=0
###< Default Jitsi Server ###

### Enterprise Settings ###
enterprise_noExternal=0
allowTimeZoneSwitch=0
emailSenderIsModerator=0
###<Enterprise Settings>###

### LDAP Settings ###
ldap_url="ldap://localhost:10389;ldap://localhost:10389"
ldap_bind_dn="uid=admin,ou=system;uid=admin,ou=system"
ldap_password=password;password
ldap_user_dn="o=meinComp,o=testOrg,dc=example,dc=com;o=testOrg,dc=example,dc=com"
ldap_user_object_classes=person,organizationalPerson,user;person,organizationalPerson,user
ldap_search_scope=sub;one
ldap_userName_attribute=uid;uid
ldap_attribute_mapper='{"firstName":"givenName", "lastName":"sn", "email":"uid"};{"firstName":"givenName", "lastName":"sn", "email":"uid"}'
ldap_bind_type=simple,none
ldap_rdn_ldap_attribute=uid,uid
ldap_uuid_ldap_attribute=objectGUID
ldap_server_individualName=ldap_1,ldap_2
###<LDAP Settings>###
</code></pre>

**Comment by holema** [comment]
Hello @Sherif-khaled,

I konw this error, it sometimes apear but is not possible to reproduce the error. I found a possibility to fix it, and I will push a fix in the next hours. I fixed it already in the feature/development branch, but I will put it here too.
Best regads

**Comment by holema** [comment]
Can you try the new version 0.71.19.


Best regards.

**Comment by Sherif-khaled** [comment]
thank you i will pull the changes

**Comment by holema** [comment]
Hello @Sherif-khaled,
is the bugfix working?

If so, please close the issue. :)
