### ISSUE TITLE
Support Time Zones?

### ISSUE THREAD

**Issue by yasurok** [H2-invent/jitsi-admin#319]
Does Jitsi Admin support time zones? I've merely created an account with the demo server and looked around so I am not absolutely sure, but it appeared that the time zone is hard wired and cannot be changed. That alone takes away most of its values away for those who do not live in whatever time zone is assumed.

I hope you'll address this issue soon.

Thanks!

**Comment by holema** [comment]
Hello @yasurok,
yes Jitsi-Admin supports timezones.

You just have to set the env-Variable
allowTimeZoneSwitch=1
and
input_settings_allow_timezone=1

After this you have to set a default timezone in your php.ini. (Important)
The users can now select their home timezone when they click on the profile button.
The conference can now be planed in the whished timezone and all users see the time in their own timezone.

**Comment by yasurok** [comment]
That's great, but why isn't it enabled on the demo server? Wouldn't you
want to showcase all its features of Jitsi Meet with it?

**Comment by yasurok** [comment]
Sorry, I meant Jitsi Admin.

**Comment by holema** [comment]
Hello @yasurok,

It´s not enabled, because it is only used by a very little set of users.
And ist is not that easy to enable it in the own installation, thats why we hide it there.

Are you running your own jitsi-admin instance?

**Comment by yasurok** [comment]
No, I don't. It could be on my roadmap in the long run, but not at the moment.

I still feel very odd about not allowing users to set their default time zone. Don't you want people from all over the world to use Jitsi Admin? 

I would think the whole reason of setting up a demo server is so people will have a chance to see how well your system works and if it fits their needs. Initially, I thought, "Wow, it does not even support specifying time zones. Who would use a system like this?" I bothered to ask here just to make sure, but I bet many people won't, quietly dismissing Jitsi Admin as not useful enough just for this one reason. 

If Jitsi Admin does support time zones, I strongly suggest you make that feature available on the demo server as well. You say the feature is not enabled because it is only used by a very little set of users. Maybe isn't it the other way around? Perhaps people do not use it because it is not enabled on the demo server, which makes people think Jitsi Admin lacks that ability entirely.

**Comment by holema** [comment]
Hello @yasurok,

up to now we activate the timezone functionaltity in the jitsi-admin intance.
![image](https://user-images.githubusercontent.com/22790152/187368894-68b0a1d8-93b8-47bd-8b6b-ab064da9ec46.png)

**Comment by holema** [comment]
You can switch your localtimezone by clicking the profile button and the change timezone. After this all conferences will be shown in your timezone. and you can set the timezone of the meeting specific.
