### ISSUE TITLE
docker-compose 2.7.0 incompatibility

### ISSUE THREAD

**Issue by danionescu2007** [H2-invent/jitsi-admin#326]
Docker.com updated their documentation page with docker-compose 2.7.0:
https://docs.docker.com/compose/install/compose-plugin/#install-the-plugin-manually

Whoever will begin with a fresh installation is safe to assume they will use this version which results in failure to build jitsi-admin in its current state.

<img width="435" alt="image" src="https://user-images.githubusercontent.com/4688610/180434908-034322b8-f38c-426a-8e97-49d08e0ec77c.png">

So perhaps it would worth a while to mention 2.6.1 version of docker-compose as a prerequisite.

**Comment by holema** [comment]
Hello @danionescu2007,

so sad, but exactly this is the improvment of version 2.7.0. 

I found a solution ;) I can fix it when I write a $$ in the .env file. I will add this hotfix this evening.

**Comment by holema** [comment]
@danionescu2007 Could you verify that the bug is fixed?

**Comment by danionescu2007** [comment]
it works like a charm
