### ISSUE TITLE
Completed the english translation for the dev branch

### ISSUE THREAD

**Issue by danionescu2007** [H2-invent/jitsi-admin#329]
<img width="778" alt="image" src="https://user-images.githubusercontent.com/4688610/180635604-1a79f2c2-124b-4d37-97f2-83ea71302264.png">
When can we see this changes in the master branch?

The latest version still contains german strings in the english translation.

Thanks.

**Comment by holema** [comment]
Hello, the changes are in the master branch, when I merge the #318 Pull Request. I try to add it tomorrow.
Thanks for helping us to translate.

Do you also need an other language to translate for? Then I can enable it for you at crowdin.

Best regards

**Comment by danionescu2007** [comment]
HI,

Great. I could translate for Romanian, if you could add the language.

**Comment by holema** [comment]
I added rumania to the list. 
Thanks for your great help.

**Comment by danionescu2007** [comment]
You're welcome. Thanks.
