### ISSUE TITLE
An exception occurred while executing a query: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'jitsiadmin.fos_user' doesn't exist

### ISSUE THREAD

**Issue by epigraphe** [H2-invent/jitsi-admin#331]
**Describe the bug**

**To Reproduce**
1. Clean install of jitsi-admin (docker-install)
2. Reg user
3. Trying to login

**Screenshots**
![image](https://user-images.githubusercontent.com/6083395/181279987-a7f34615-7775-4b97-bd15-9ace46ccde2b.png)

**Desktop (please complete the following information):**
 - OS: Win11
 - Browser chrome

**Comment by holema** [comment]
Hello @epigraphe,
Which Version do you use for the installation?

This error occurs, when the schema in the database is not created correctly.
On which OS did you install the jitsi-admin?

did you setup the jitsi-admin in dev or prod mode?

**Comment by holema** [comment]
I think I found the error. It seems you are using the local dev environment. There were some breaking changes we did in the prod docker-compose file and we did not migrate this to the docker-compose test.

So 0.73.6 should fix this issue. Just make a `git pull` on the master branch and try to reinstall the jitsi-admin with `bash installDocker.sh`

**Comment by epigraphe** [comment]
Trying to reinstall anf got next erorr:
```

ERROR: Version in "./docker-compose.test.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```

Ubuntu 20,04 dev mode

**Comment by holema** [comment]
what version of docker-compose do you use? I had to increase the docker-compose version to 3.8, because service healty is only support after 3.8

**Comment by epigraphe** [comment]
docker-compose version 1.25.0, build unknown

**Comment by holema** [comment]
The latest official docker-compose is 2.7.0 but ubuntu is not refreshing their repo so fast.

Can you try to set the version of the docker-compose.test.yml manually to 3.7 if this is working, I can revert the docker-compose version to 3.7

```
#docker-compose.test.yml
version: '3.7'
```

**Comment by epigraphe** [comment]
Changed to 3.7 
```
ERROR: The Compose file './docker-compose.test.yml' is invalid because:
services.app-ja.depends_on contains an invalid type, it should be an array
services.keycloak-ja.depends_on contains an invalid type, it should be an array
```

**Comment by holema** [comment]
Which docker engine do you have installed?

**Comment by epigraphe** [comment]
n# docker version
Client: Docker Engine - Community
 Version:           20.10.17
 API version:       1.41
 Go version:        go1.17.11
 Git commit:        100c701
 Built:             Mon Jun  6 23:02:57 2022
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.17
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.17.11
  Git commit:       a89b842
  Built:            Mon Jun  6 23:01:03 2022
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.6
  GitCommit:        10c12954828e7c7c9b6e0ea9b0c02b01407d3ae1
 runc:
  Version:          1.1.2
  GitCommit:        v1.1.2-0-ga916309
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by holema** [comment]
The docker engine is correct. It must be >19.03.0

Could you install the latest docker-compose manually? This is the fastest way https://docs.docker.com/compose/install/compose-plugin/#install-the-plugin-manually
I tested it with docker-compose 2.4 and 2.7 and then it is working.

**Comment by epigraphe** [comment]
Done, but have the same problems:
v3.8
```
ERROR: Version in "./docker-compose.test.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
For more on the Compose file format versions, see https://docs.docker.com/compose/compose-file/
```
v.3.7 
```
ERROR: The Compose file './docker-compose.test.yml' is invalid because:
services.app-ja.depends_on contains an invalid type, it should be an array
services.keycloak-ja.depends_on contains an invalid type, it should be an array
```



```
:/var/www/jitsi-admin# docker compose version
Docker Compose version v2.7.0
/var/www/jitsi-admin# docker-compose version
docker-compose version 1.25.0, build unknown
docker-py version: 4.1.0
CPython version: 3.8.10
OpenSSL version: OpenSSL 1.1.1f  31 Mar 2020
```

**Comment by holema** [comment]
I use in the bash script docker-compose. 
I haven`t installed it as a plugin.

with this you can directly download it into your bin directory. I did it this way.
```
curl -SL https://github.com/docker/compose/releases/download/v2.7.0/docker-compose-linux-x86_64 -o /usr/local/bin/docker-compose
chmod +x  /usr/local/bin/docker-compose
docker-compose -v
```

**Comment by epigraphe** [comment]
Finally it works
Uninstalled docker-plugin and again trying with v3.8
Setup proccess was completed.
Unfortunately, now when i try to open jitsi-admin and traefik in the browser, i get a 404 not found error and keycloak showing bad gateway.
But I think this issue can be closed, because these are other problems.
Thank you for your time. You are the greatest.

**Comment by holema** [comment]
It can take some minutes until the keycloak is up.
sometimes when you are low on ram, the traefik is not registering the container. then try `docker restart <traefik containerid>`

can you send me the logs of the keycloak and the jitsi-admin?

you can get it with `docker logs <containerid>`

The development installation is quite instable, because there are so many dependencied and the conainers have to communicate which is not optimal without https. We only use this for the first prototyping.

So if you have any chance to install it with the prod environmant, then everything works much better. You just need a external domain or subdomain,

**Comment by epigraphe** [comment]
Basically, these were problems with my virtual machines.
On your advice, I moved to the prod version. I don’t have a certificate yet, I need to forward port 80 for letsencrypt, I’ll add it a little later.
keycloak works, lets me into the admin area. traefik also works, lets me into the dashboard
I created a user in the keycloak admin panel and when I try to log in with his credentials I get an error 500.
I didn't see any errors in keycloak logs

[https://pastebin.com/frmZpb5F](https://pastebin.com/frmZpb5F)

But there are errors in mariadb logs
```
2022-07-28 10:33:57 124 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2022-07-28 10:34:27 128 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2022-07-28 10:34:57 130 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2022-07-28 10:35:27 134 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
2022-07-28 10:35:57 136 [Warning] Access denied for user 'root'@'localhost' (using password: NO)
```

I suppose this is due to the fact that I do not have a certificate yet?

**Comment by h2Entwicklung** [comment]
this happens, because the jitsi-admin wants to get the user informations. this is plain OpenID-Connect.
But this doesnt works, becaue you don`t have an valid certificate. 
So the 500 error is completly correct on the jitsi-admin side.
