### ISSUE TITLE
Problem with the lobby

### ISSUE THREAD

**Issue by supczinskib** [H2-invent/jitsi-admin#356]
Hi,

I'm having trouble joining a conference with the lobby option turned on. The effect as in the attached video. Could you tell me where to look for the cause of this problem?

https://user-images.githubusercontent.com/40168732/212206654-dbae2ab6-5215-4956-848a-80e895223c3a.mp4

**Comment by holema** [comment]
Hello, which version do you use?
Is this the Version 0.74.x or Version 0.75.0-RCX?
I think you use the version 0.74.x and in this case you have to use the old Mercure hub.
The Mercure Hub has to be installaed as described here:
https://github.com/H2-invent/jitsi-admin/wiki/Install-Mercure-hub-for-realtime-communication-(SSE)----This-is-necessary-for-the-new-lobby-function

Did it work before?

**Comment by supczinskib** [comment]
> Hello, which version do you use? Is this the Version 0.74.x or Version 0.75.0-RCX? I think you use the version 0.74.x and in this case you have to use the old Mercure hub. The Mercure Hub has to be installaed as described here: https://github.com/H2-invent/jitsi-admin/wiki/Install-Mercure-hub-for-realtime-communication-(SSE)----This-is-necessary-for-the-new-lobby-function
> 
> Did it work before?

I am using version 0.74.1. Haven't used the lobby before so don't know if it worked. I'll check the Mercure hub again tonight and get back to you. Thank you very much for the tip.

**Comment by holema** [comment]
I´m happy to help you.

The mercure Hub was just a bridge for us. In the version 0.75.x we drop mercure an build a completly own websocket solution which works much more solid. I´m just on the way to build a new install script. As asked in #355

**Comment by supczinskib** [comment]
> I´m happy to help you.
> 
> The mercure Hub was just a bridge for us. In the version 0.75.x we drop mercure an build a completly own websocket solution which works much more solid. I´m just on the way to build a new install script. As asked in #355

The Mercure Hub appears to be working, but unfortunately the attendee is stuck in the lobby forever :)


`{"level":"info","ts":1673746420.65887,"caller":"mercure/handler.go:118","msg":"Mercure started","protocol":"http","addr":"localhost:3000"}`

Attempting to join a participant to the conference and waiting in the lobby:

`{"level":"info","ts":1673746446.2885606,"caller":"mercure/publish.go:82","msg":"Update published","update":{"id":"urn:uuid:d6682f9f-89a3-4d17-9996-ed2f3ed22668","type":"","retry":0,"topics":["lobby_moderator/fdd2e1aeab0752f284a175204f00eee8"],"private":false},"remote_addr":"127.0.0.1:40110"}
127.0.0.1 - - [15/Jan/2023:02:34:06 +0100] "POST /.well-known/mercure HTTP/1.1" 200 45 "" "Symfony HttpClient/Curl"
{"level":"info","ts":1673746447.2984157,"caller":"mercure/publish.go:82","msg":"Update published","update":{"id":"urn:uuid:3cc23370-ca52-4899-bb09-9ad51122c8f7","type":"","retry":0,"topics":["personal/69210acf99fbae17999cff4ffef52153"],"private":false},"remote_addr":"127.0.0.1:40110"}
127.0.0.1 - - [15/Jan/2023:02:34:07 +0100] "POST /.well-known/mercure HTTP/1.1" 200 45 "" "Symfony HttpClient/Curl"
{"level":"info","ts":1673746447.3055143,"caller":"mercure/publish.go:82","msg":"Update published","update":{"id":"urn:uuid:ff010e67-f4a4-4e1e-b3fb-78e614e21e5e","type":"","retry":0,"topics":["lobby_moderator/fdd2e1aeab0752f284a175204f00eee8"],"private":false},"remote_addr":"127.0.0.1:40110"}
127.0.0.1 - - [15/Jan/2023:02:34:07 +0100] "POST /.well-known/mercure HTTP/1.1" 200 45 "" "Symfony HttpClient/Curl"`

An attempt to access the conference was granted by a moderator:

`{"level":"info","ts":1673746454.1157277,"caller":"mercure/publish.go:82","msg":"Update published","update":{"id":"urn:uuid:90bba9cc-b20d-4102-ae8f-04245d0fbf01","type":"","retry":0,"topics":["lobby_WaitingUser_websocket/0609e480b58221213d3d0a0b0b56116f"],"private":false},"remote_addr":"127.0.0.1:51464"}
127.0.0.1 - - [15/Jan/2023:02:34:14 +0100] "POST /.well-known/mercure HTTP/1.1" 200 45 "" "Symfony HttpClient/Curl"
{"level":"info","ts":1673746454.11827,"caller":"mercure/publish.go:82","msg":"Update published","update":{"id":"urn:uuid:5f60a3f4-bae5-433b-b29d-9ea59c06296a","type":"","retry":0,"topics":["lobby_WaitingUser_websocket/0609e480b58221213d3d0a0b0b56116f"],"private":false},"remote_addr":"127.0.0.1:51464"}
127.0.0.1 - - [15/Jan/2023:02:34:14 +0100] "POST /.well-known/mercure HTTP/1.1" 200 45 "" "Symfony HttpClient/Curl"
{"level":"info","ts":1673746454.1188016,"caller":"mercure/publish.go:82","msg":"Update published","update":{"id":"urn:uuid:2208cc1f-ce92-4ee3-93ea-1a04af8749d8","type":"","retry":0,"topics":["lobby_WaitingUser_websocket/0609e480b58221213d3d0a0b0b56116f"],"private":false},"remote_addr":"127.0.0.1:51464"}
127.0.0.1 - - [15/Jan/2023:02:34:14 +0100] "POST /.well-known/mercure HTTP/1.1" 200 45 "" "Symfony HttpClient/Curl"
{"level":"info","ts":1673746454.1193504,"caller":"mercure/publish.go:82","msg":"Update published","update":{"id":"urn:uuid:c7119c37-9827-4b62-bcc7-8a27bafcab0d","type":"","retry":0,"topics":["lobby_moderator/fdd2e1aeab0752f284a175204f00eee8"],"private":false},"remote_addr":"127.0.0.1:51464"}
127.0.0.1 - - [15/Jan/2023:02:34:14 +0100] "POST /.well-known/mercure HTTP/1.1" 200 45 "" "Symfony HttpClient/Curl"
{"level":"info","ts":1673746454.1203237,"caller":"mercure/publish.go:82","msg":"Update published","update":{"id":"urn:uuid:370177c3-7771-499e-b4e7-c66d380393d4","type":"","retry":0,"topics":["personal/69210acf99fbae17999cff4ffef52153"],"private":false},"remote_addr":"127.0.0.1:51464"}
127.0.0.1 - - [15/Jan/2023:02:34:14 +0100] "POST /.well-known/mercure HTTP/1.1" 200 45 "" "Symfony HttpClient/Curl"
{"level":"info","ts":1673746454.120822,"caller":"mercure/publish.go:82","msg":"Update published","update":{"id":"urn:uuid:2e584c95-80db-4d2f-9c9b-b50aa103ef85","type":"","retry":0,"topics":["lobby_moderator/fdd2e1aeab0752f284a175204f00eee8"],"private":false},"remote_addr":"127.0.0.1:51464"}
127.0.0.1 - - [15/Jan/2023:02:34:14 +0100] "POST /.well-known/mercure HTTP/1.1" 200 45 "" "Symfony HttpClient/Curl"`

**Comment by holema** [comment]
Hello @supczinskib,

when you open the browser log of the participant. And when you select the network tab, can you see the mercure hub request?
Here you should see a HTTP-request which is staying open foreever.
Have you set the env variable that the frontend connect to mercure as well. The Log shows that backend can send messages to the mercure, but I´m not sure if the frontend is connected to the mercure.

**Comment by supczinskib** [comment]
> Hello @supczinskib,
> 
> when you open the browser log of the participant. And when you select the network tab, can you see the mercure hub request? Here you should see a HTTP-request which is staying open foreever. Have you set the env variable that the frontend connect to mercure as well. The Log shows that backend can send messages to the mercure, but I´m not sure if the frontend is connected to the mercure.
> 
> ```
> ###> symfony/mercure-bundle ###
> # See https://symfony.com/doc/current/mercure.html#configuration
> # The URL of the Mercure hub, used by the app to publish updates (can be a local URL)
> MERCURE_URL=http://localhost:3000/.well-known/mercure
> # The public URL of the Mercure hub, used by the browser to connect
> MERCURE_PUBLIC_URL=http://localhost:3000/.well-known/mercure
> # The secret used to sign the JWTs
> MERCURE_JWT_SECRET=test
> ###< symfony/mercure-bundle ###
> ```

Die Variable MERCURE_PUBLIC_URL fehlte in der Konfiguration. Ich habe zuvor MERCURE_URL einen Wert zugewiesen und dachte, das würde ausreichen. Jetzt funktioniert die Lobby einwandfrei. Vielen Dank für Ihre Hilfe und einen schönen Tag.
