### ISSUE TITLE
Customization of the user interface

### ISSUE THREAD

**Issue by supczinskib** [H2-invent/jitsi-admin#357]
Can you post some sample theme files. I would like to see what are the possibilities of personalizing the application in the commercial version.

**Comment by holema** [comment]
Hello @supczinskib,

You can have a look at [app.meetling.de/join](https://app.meetling.de/join)
There we have a sample theme implemented.

If you login to https://app.meetling.de Then you can see the theme and what is possible.

You can write me on entwicklung@h2-invent.com so I can explain you more about the theming.
In the Theme you can define besides each env-variable all colors ans all logos and icons in the top bar.

**Comment by supczinskib** [comment]
Thank you. This information is enough for me. I have one more question. What needs to be done for the screen sharing lock feature to work. Even though I set: enableFeaturesBasedOnToken: true in Jitsi Meet, anyone can share their screen. However, in Jitsi Admin, like on the demo server, there is no option to disable this feature in the menu for individual users. I have the `input_settings_dissallow_screenshare` variable set to `1`. JWT is enabled and works fine. Jitsi Meet recognizes who is a participant and who is a moderator of the conference.

<img width="559" alt="screen" src="https://user-images.githubusercontent.com/40168732/214756388-3a811ed9-9fad-467c-99fd-0c68152b2a93.png">

**Comment by holema** [comment]
Hello,
The function has to be activated in the server settings. This only has to be done once.
![image](https://user-images.githubusercontent.com/22790152/214773346-096bb017-e264-447e-85cd-640679544298.png)

Then when a moderator creates a conference then he can select if there is a restriction on screenshare
![image](https://user-images.githubusercontent.com/22790152/214773567-68c2100d-676a-41ee-982f-ae0802855742.png)

Now you can set the permission to each user
![image](https://user-images.githubusercontent.com/22790152/214773785-9bb9b1d1-26fc-435c-9fe8-6b3df5200dc6.png)

**Comment by supczinskib** [comment]
Thanks for the clarification. For some reason I don't have this option in the menu at all. Do you have any suggestions where to look for the problem.

https://user-images.githubusercontent.com/40168732/214918300-a7782bc7-5309-4297-b987-79e31cdbe5ba.mp4

**Comment by holema** [comment]
Thanks @supczinskib,

I will have a look. It should be there. I will double check it

**Comment by holema** [comment]
Hello @supczinskib,
I found the bug and fixed it in a hotfix. When the PR is approved, I will make a new version with this fix.

**Comment by supczinskib** [comment]
Thansk, You can upload the patch here?

**Comment by supczinskib** [comment]
Thanks!

**Comment by holema** [comment]
If you want, you can checkout this branch for 0.74.x
https://github.com/H2-invent/jitsi-admin/tree/hotfix/screenshare_enable_default
It would be great if you can check the fix.

**Comment by supczinskib** [comment]
I already checked. Everything works correctly. When JWT is disabled, there are no options in the menu. When enabled, the option is visible. The feature itself in Jitsi Meet works fine. Thank you again.

<img width="1245" alt="2" src="https://user-images.githubusercontent.com/40168732/214954313-4fd1f7d3-615f-4c7b-bd8d-c4a8aeae6c80.png">

**Comment by holema** [comment]
https://github.com/H2-invent/jitsi-admin/releases/tag/0.74.2 solves this issue.
