### ISSUE TITLE
Keycloak Group To Create Server

### ISSUE THREAD

**Issue by supczinskib** [H2-invent/jitsi-admin#361]
Hi,

Whether "laf_keycloakGroupToCreateServer" has been implemented. Even though I've added myself to the /user group in Keycloak (version 17), I can't see the server configuration icon. Maybe I should set something extra in Keycloak?

`laf_CreateServerOpenToEveryone=0`
`laf_keycloakGroupToCreateServer=/user`

<img width="683" alt="Zrzut ekranu 2023-02-3 o 18 37 43" src="https://user-images.githubusercontent.com/40168732/216670198-fbbf981b-0855-477b-9d50-b6285e0e987c.png">

**Comment by holema** [comment]
Hello @supczinskib,
sorry for the late reply,
did you create a group mapper in KC?
I described it here in the wikik how to create the correct mapper:
https://github.com/H2-invent/jitsi-admin/wiki/Organize-Jitsi-Servers-via-keycloak-groups

**Comment by supczinskib** [comment]
Thank you, This is exactly what I was missing. Now everything works as it should.
<img width="673" alt="groups" src="https://user-images.githubusercontent.com/40168732/217559068-9af3577c-f99b-4a0b-a8fa-08f33a15bd5c.png">

**Comment by holema** [comment]
I´m happy that I could helped you with this issue
