### ISSUE TITLE
New conference error: date in the past

### ISSUE THREAD

**Issue by kiroubel-girma** [H2-invent/jitsi-admin#362]
**Describe the bug**
Cannot create a conference for later in the day (today): "Error, start and end date are in the past."
It's time and timezone related, probably a bug when your timezone is behind UTC.

**To Reproduce**
My timezone is Toronto, currently UTC -5 hours.
If I select a time for later today, less than the UTC offset (5 hours) away, I see the error.
I have noticed that the date/time selector is in German (default locale), while I have switched to English locale, not sure if it matters.

**Screenshots**
![image](https://user-images.githubusercontent.com/91738118/224333693-bc99f99b-72bc-4143-a1f2-93a82d416548.png)
![image](https://user-images.githubusercontent.com/91738118/224334826-05068620-9ffe-4903-8df8-6bd4a5b9ad9e.png)

I am running the docker install.

**Comment by holema** [comment]
Hello @kiroubel-girma,

which branch are you using?
I will try it so I can giv you a feedback.

**Comment by holema** [comment]
Hello @kiroubel-girma ,
I found the bug and fixed it in the attached PR. I think it will be merged tomorrow.

Best regards and thanks for your help.

**Comment by holema** [comment]
Hello @kiroubel-girma,
this bug should be fixed now in the latest master. To install just type `git pull` and then start the deployment of your docker with `bash installDocker.sh` to rebuild the application.
The bug will be merged into the freeze branch today or tomorrow, if you are using the RC-branch.
