### ISSUE TITLE
Docker Install: mercure-ja restarting

### ISSUE THREAD

**Issue by kiroubel-girma** [H2-invent/jitsi-admin#366]
**Describe the bug**
I am using the latest master, with a docker install
I see that `mercure-ja ` service keeps restarting.

**Branch or Version you using**
Master (0.74.4)

**Workaround**
Use a previous docker image (latest is 0.14.5, and same issue with 0.14.4)
`dunglas/mercure:v0.14.3` image works.

**Comment by holema** [comment]
Hello @kiroubel-girma,

Thanks for reporting this isue.

I will check this problem, but we face the issue, that we don´t know what mercure is developing. We faced a lot of similar issues with mercure in the past so we decided to drop mercure in version 0.75.x . In this new version we completly build our own websocket service which is way more robust and we have fully control for what is going on with the realtime communication.

I would suggest that you pull the freeze/0.75.x branch and deploy that version.
For debbuging reasons, can you give me the logs from your mecure container? You can get it with `docker logs mercure-ja`
