### ISSUE TITLE
Invalid parameter: redirect_uri (Jitsi-admin in Docker)  

### ISSUE THREAD

**Issue by yoitcj** [H2-invent/jitsi-admin#368]
Hi,
is there any clue how to correct "redirect_uri" data when i click register button.
in my situation, redirect_uri data comes with double data like "https://mydomain.comhttps:/mydomain.com/login/keycloak_login/check" that give me error invalid parameter: redirect_uri 
when i remove one data directly in browser url so become https://mydomain.com then the register form of keycloak show up and the register process successfully create user in jitsi-admin

thank you,

**Comment by holema** [comment]
Hello, which Version do you use?
I will try it on my installation and then give you a feedback.

**Comment by yoitcj** [comment]
i'm sorry i don't know to find the version.
i install jitsi-admin following this instruction https://github.com/H2-invent/jitsi-admin/wiki/Install-jitsi-admin-in-docker
yesterday
when i'm login  in jitsi-admin, i found thisr 2023-v00447 in the bottom bar

**Comment by holema** [comment]
Hello, thanks. This is the commit hash and helps me a lot.

I just research the issue and I´m able to reproduce it on docker but not in my dev environment.

Best regards
Emanuel

**Comment by h2Entwicklung** [comment]
You can download this version or make git pull in your directory to get the latest version. Then restart the installation process with `bahs installDocker.sh` The settings you made are persistant.

https://github.com/H2-invent/jitsi-admin/releases/tag/0.74.6

Best regards
