### ISSUE TITLE
Add translation to Brazilian Portuguese to Crowdin

### ISSUE THREAD

**Issue by LeoColman** [H2-invent/jitsi-admin#374]
Hello!

I'm Brazilian and would like to contribute in translating jitsi-admin from English to Portuguese. I know English is not 100% complete yet

I'm not able to make the translation as it's disabled in crowdin.

**Comment by holema** [comment]
Hello @LeoColman,
I added brazilian to crowdin.
Tanks a lot for ypur help
https://crowdin.com/project/jitsi-admin/pt-BR

Best regards

**Comment by LeoColman** [comment]
Perfect!
Thanks.

I've done a couple of translations already, and damn! There are many Strings!
Thanks for adding PT-BR to Crowdin :)

**Comment by holema** [comment]
I alread saw it.
Yes the application is growing constantly ;) So we need a lot of strings.

I will merge it for the next release andI will add it as a langauge Selector in the navbar.
