### ISSUE TITLE
cant see manage participant form after planning conference

### ISSUE THREAD

**Issue by 297297sid** [H2-invent/jitsi-admin#397]
Sir as i am planning conference in my admin interface after saving conference , it doesn't take me to manage participant form . Can u pls tell how do i fix it . if it doesnt take me to manage participant form ,i cant able to enter participant nd moderator mails in it . HOw do i fix it.

**Comment by holema** [comment]
This issue was fixed in the versoin 0.75.4.
The issue with the SMTP-server is bcause of a wrong configured SMTP-Server.

**Comment by 297297sid** [comment]
ok
