### ISSUE TITLE
Conference ID not populating in link 

### ISSUE THREAD

**Issue by gradark** [H2-invent/jitsi-admin#410]
1. If copy link from Admin Panel , when invitee opens link , it's not populating Conference ID
it ask for CONFERENCE ID , and visitor can not enter the conference after opening link , if the link can automatically pickup conference id will be helpful for invitees .
2. Also how to disable authentication of invitees , as once invitee feels the Name , Email , he is asked to confirm email id. 

Please help to resolve the issue .
![Screenshot (197)](https://github.com/H2-invent/jitsi-admin/assets/134778423/8e77d051-0f9b-4550-babc-6e52bfe73eab)
![Screenshot (198)](https://github.com/H2-invent/jitsi-admin/assets/134778423/4b2b1820-2394-45a3-af84-f4d1ee7dc293)

Regards
VK

**Comment by holzi1005** [comment]
Hi @gradark 
it is not an issue. This function is the normal workflow of Jitsi Admin. You can read the wiki and FAQ to see how it works.
