### ISSUE TITLE
Get 500 error after login 

### ISSUE THREAD

**Issue by hiteshsaini33** [H2-invent/jitsi-admin#431]
1. Setup Jitsi admin with docker
2. Register User

When try to login with that user, get 500 error on latest version.

<img width="2560" alt="image" src="https://github.com/H2-invent/jitsi-admin/assets/73432782/1d593504-cbb9-41d3-ba13-45ac142044e2">

<img width="2381" alt="image" src="https://github.com/H2-invent/jitsi-admin/assets/73432782/9fd031f4-044b-4673-9ca0-f93cf6be3c48">

This is in the log

**Comment by holema** [comment]
Hello @hiteshsaini33,

did it work with an older version?
Best regads

**Comment by hiteshsaini33** [comment]
login page works in 0.75.5 but that version also doesn't work correctly. last version which works good is 0.75.0

**Comment by holema** [comment]
OKay, then I will test it.

**Comment by hiteshsaini33** [comment]
Ok, great. Pls let me know here after done testing.

**Comment by holema** [comment]
Hello @hiteshsaini33,

can you try the hotfix branch: hotfix/analytics
https://github.com/H2-invent/jitsi-admin/tree/hotfix/analytics

**Comment by hiteshsaini33** [comment]
Ok, great, I test it and let you know

**Comment by hiteshsaini33** [comment]
Hello @holema 

Yes It is working with this branch.

**Comment by holema** [comment]
Hello @hiteshsaini33,

I merged it in the master, so the latest version has the fix. Thanks for your help

**Comment by hiteshsaini33** [comment]
Welcome @holema and Thank you for your help too.
