### ISSUE TITLE
Docker install error

### ISSUE THREAD

**Issue by dbakushkin** [H2-invent/jitsi-admin#442]
I am using the latest master, with a docker install and I get an error on installation step. Can you help?
OS  Ubuntu 22.04.3 

![Screenshot_1](https://github.com/H2-invent/jitsi-admin/assets/93332794/b2798d23-57ee-4fd8-817c-29d37637aab1)

**Comment by holema** [comment]
Hello @dbakushkin,

do you start the installation with a root account?

**Comment by holema** [comment]
I just try to install it on my maschine to get the error

**Comment by holema** [comment]
You try to start the system via docker-compose up, or do you use the `sudo bash installDocker.sh` command?

**Comment by holema** [comment]
can you try to set the user to root in the Dockerfilfe which is located in nodejs/Dockerfile.
You can do this by changing line 4 `USER node``to `USER root`. Then you can try it again. If this is working I will double check why it is not working on your system.

**Comment by holema** [comment]
you can also try to checkout branch `hotfix/errorpage`
