### ISSUE TITLE
Recording problem

### ISSUE THREAD

**Issue by supczinskib** [H2-invent/jitsi-admin#444]
Hi,

When I join a video conference using Jitsi Admin, I don't have a record button using jibri. When I disable token authentication in prosody (token_verification and token_moderation) and enter Jitsi Meet directly, recording is available. Is there a way to solve this problem?

**Comment by holema** [comment]
Hello @supczinskib,
Usually, we refrain from altering the default button settings, as they are preconfigured within Jitsi-Meet. While the iFrame API offers the capability to activate or deactivate buttons, this feature isn't currently used within the Jitsi-admin .

Later today, I'll dedicate some time to investigate this matter further. I'll explore if this behavior is consistent across various Jitsi configurations – whether it's a standard Jitsi window, or a conference with lobby enabled. There the participant side and the moderator side is interesting.

**Comment by supczinskib** [comment]
I will add that with the same configuration (verification and moderation plugin disabled) when I join the conference from Jitsi Admin, there is no record button. If I skip admin Jitsi, the record button will be available. In the video, the interface is in Polish, but I think the message is clear.  The jibri and jicofo logs look the same in both situations.

https://github.com/H2-invent/jitsi-admin/assets/40168732/c026f8ce-fb19-47b5-9c55-67136e830e3c

**Comment by supczinskib** [comment]
You can close the request. I've already done it. Thanks for the help.

**Comment by holema** [comment]
Hello @supczinskib
,
how did you fix it? This is propably for others interesting too :)

Thanks for helping to make the project better.

**Comment by supczinskib** [comment]
I'm recording in a client-side browser.

**Comment by halsbox** [comment]
> Hello @supczinskib , how did you fix it? This is propably for others interesting too :)
> 
> Thanks for helping to make the project better.

Hi. I had a same problem. Solved by hardcoding `'recording' => true` to `$payload['context']['features']` of JWT Token inside `src/Service/RoomService.php`. Also did same for `'livestreaming' => true`.
