### ISSUE TITLE
Problem with special characters in smtpPassword in docker.conf

### ISSUE THREAD

**Issue by gibimani** [H2-invent/jitsi-admin#454]
The installation script "installDocker.sh" asks for a smtpPassword and writes it to the file docker.conf. Special characters like "$" are written to the file the first time but starting "installDocker.sh" a second time or more strips special characters from the password.

A potential fix could be something like this:
```
  smtpPassword=${smtpPassword:=password}
  read -rp "Enter smtp password [$smtpPassword]: " input
  smtpPassword=${input:=$smtpPassword}
  smtpPassword_tmp=$(printf "%q" "$smtpPassword")
  sed -i '/smtpPassword/d' $FILE
  echo "smtpPassword=$smtpPassword_tmp" >> $FILE
```

**Comment by holema** [comment]
Hello @gibimani ,
can you try: 
```
  smtpPassword=${smtpPassword:=password}
  read -p "Enter smtp password [$smtpPassword]: " input
  smtpPassword=${input:=$smtpPassword}
  sed -i '/smtpPassword/d' $FILE
  echo "smtpPassword='$smtpPassword'" >> $FILE
```

I think then it should work. If it is working, then I will add this to a fix.

**Comment by gibimani** [comment]
Hello holema,
i can confirm your fix works. Thank your :)
