### ISSUE TITLE
Option menu can't expand all entries

### ISSUE THREAD

**Issue by gibimani** [H2-invent/jitsi-admin#455]
Klicking the "Optionen" button of a conference opens a menu which looks like this:
![image](https://github.com/H2-invent/jitsi-admin/assets/146032885/7e2a5a58-0311-48b0-8126-50c1f9aa65d7)
This happens when the browser is working in full screen mode, resizing the browser window until only the symbols of the menu are visible (like in the picture)  makes all entries in the option menu appear.
![image](https://github.com/H2-invent/jitsi-admin/assets/146032885/ac34c5f5-ffe9-4684-9f8b-17691597df89)
- Firefox 118.0.1 on Windows
- Full HD resolution

**Comment by holema** [comment]
Hello @gibimani,

This issue will be fixed in the next release.
This only happens when there is only one conference. When you add an other conference it will work.

**Comment by holema** [comment]
is fixed in the version 0.77.0
