### ISSUE TITLE
default jitsi server configuration

### ISSUE THREAD

**Issue by baby-leo** [H2-invent/jitsi-admin#456]
i am trying to make multiple jitsi servers as a default servers on jitsi admin, could you please show me how to do that.

**Comment by holema** [comment]
Hello @baby-leo,
what exactly do you want to do? what do you mean with default server? And do you have your own jitsi-admin installation?

**Comment by baby-leo** [comment]
yes i have my own jitsi admin server installation running. what i want to do is to
have multiple jitsi servers to be accessible for the users with out them adding it just like this 
![Screenshot from 2023-10-05 11-10-39](https://github.com/H2-invent/jitsi-admin/assets/59183394/b78d7ba4-dd58-49d6-987c-9338834ed011)

**Comment by baby-leo** [comment]
mine looks like this
![Screenshot from 2023-10-05 11-09-54](https://github.com/H2-invent/jitsi-admin/assets/59183394/afea26e0-7813-4ecb-a4a2-42dc51f128d9)

**Comment by baby-leo** [comment]
mine looks like this and i want both to be default
![Screenshot from 2023-10-05 11-30-14](https://github.com/H2-invent/jitsi-admin/assets/59183394/002303b8-34a0-47cd-bf8a-ee545b4de48e)

**Comment by holema** [comment]
Now I understand your qustion.
You can only set one server as a default server in the env file.
But I would suggest you this way:
add all users which are registered to the keycloak into a group. we call this group "all".
than add in the server settings the keycloakgroup "/all" to th allowed keycloak groups
![image](https://github.com/H2-invent/jitsi-admin/assets/22790152/1bc91644-f941-4ed4-a8ed-4d49e254ff75)

After this all users who are in the keyclok grup can organize meetings with this server.

**Comment by holema** [comment]
My screenshot is from the latest  version which was released yesterday :)

**Comment by holema** [comment]
Here is an example how to organize servers via keycloak: https://github.com/H2-invent/jitsi-admin/wiki/Organize-Jitsi-Servers-via-keycloak-groups

**Comment by baby-leo** [comment]
i have followed this instraction, where can i add keycloakgroup "/all"

**Comment by holema** [comment]
in your server setting. the last point.

**Comment by holema** [comment]
![image](https://github.com/H2-invent/jitsi-admin/assets/22790152/6857c937-7acc-43b0-b1b1-723486e04a20)
when you click on the button a new input will appear

**Comment by baby-leo** [comment]
yes i have alredyy added that too
![Screenshot from 2023-10-05 11-42-11](https://github.com/H2-invent/jitsi-admin/assets/59183394/0be7a2df-7885-4a00-96ae-9046a27054ad)

**Comment by holema** [comment]
there should be /all insert.
The groups claim is automatically read from the SSO token

**Comment by holema** [comment]
![image](https://github.com/H2-invent/jitsi-admin/assets/22790152/c101794b-1175-4dd1-821c-3a45ea566fed)

**Comment by baby-leo** [comment]
shuld i add all the users in my keycloak to the group?

**Comment by holema** [comment]
for the existing user you have to do this one time manually, but you can set the keeycloak group as default group, then all user in the future will be added to this group atomatically.
