### ISSUE TITLE
Missing Features: User & Group Restrictions/Permissions

### ISSUE THREAD

**Issue by Beleggrodion** [H2-invent/jitsi-admin#471]
Thanks to #465 had now a running test installation of jitsi-admin on my docker server, together with a jitsi instance. With some tweaks in the compose file and add of "extra_hosts" with internal ip's , because the docker server is behind a firewall. Also some other changes because traefik is already globaly running on the docker host for other docker instances (ex. the mentioned jitsi instance).

Now i had some questions, perhaps i don't find the settings or it's currently not possible. (or only possible via ldap/sso)

Is it possible to disable/restrict the registration? I mean when i wan't to use it personally with 2-3 people which open meetings, i don't want that anybody can make a account. On my matrix server i restricted the registration to some domains, and later switcher to the nice synapse admin ui. 

Also i miss the management of the currently registered user. how can i delete them? in the keycloak admin i don't find anything, so the users are in the mariadb.

Also i miss some user right levels, so currently each registered user can add and remove servers. I only want one user, which can add user and set the jwt parameters (app-id and secret) and that i can set, which user can see this server.

Perhaps this is all possible with an ldap and then sso, but for a small setup with only 2-3 people a complete ldap backend is too much for my opinion.

**Comment by holema** [comment]
The user managment happens completely on keycloak.
The jitsi-admin doesn`t include any user managment components.

You can deactivate the user registration on the keycloak side. There in the realm-setting --> Login-->User registration you can disable the user registration.

In Keycloak it is also possible to create a domain whitelist for emails, so only whitelisted email domains are allowedto register on the keycloak plattform.
https://github.com/micedre/keycloak-mail-whitelisting

**Comment by Beleggrodion** [comment]
Thanks. This helped me alot. Now i found also the users in the keycloak admin gui. I looked in the wrong realm ;-)

I added a additonal volume to the keycloak docker service, and put the jar from your link into it.

```
    volumes:
      - /data/jitsi-meet-admin/keycloak/config:/opt/keycloak/data/import:Z
      - /data/jitsi-meet-admin/keycloak/providers:/opt/keycloak/providers:Z

```

**Comment by holema** [comment]
Thanks for the tips. This will help other a lot.
