### ISSUE TITLE
the first person to enter the meeting is by default promoted to  moderator

### ISSUE THREAD

**Issue by baby-leo** [H2-invent/jitsi-admin#488]
hello jitsi admin team,
after i am running 0.75 version jitsi admin and customized jitsi meet server locally.  but after inviting participants, the first participant to enter the meeting room is by default becoming a moderator even if there are moderators with moderator link, the system is promoting the first participant. how can i fix this issue.

**Comment by holema** [comment]
Hello @baby-leo,

do you use the JWT authentication for pretecting your jitsi-server?
The moderator function only works when the JWT Token Moderator Plugin is activated in your jitsi installation?

**Comment by holema** [comment]
The license key is not used anymore. In the latest version the license key was removed.

Can you past a sample JWT here in the chat, so I can test it.

Best regards

**Comment by baby-leo** [comment]
jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJqaXRzaV9hZG1pbiIsImlzcyI6IjAwMTEyMjMzIiwic3ViIjoibWVldGRlYm8uYWlpLmV0Iiwicm9vbSI6Im1vZHRlc3QtMzA0IiwiY29udGV4dCI6eyJ1c2VyIjp7Im5hbWUiOiJEZWJvIEFkbWluIn19LCJtb2RlcmF0b3IiOnRydWV9.sOSIj-V7Nsp9dDI4pRtbQt2tXBtKSmU8yxIkVBGHVZ0

**Comment by holema** [comment]
Hello @baby-leo,
Your JWT appears to be in excellent shape! Upon thorough testing in my Testsystem, everything functions seamlessly.
Please try your system by removing the app Id and App secret from the jitsi admin. I you are still able to accessyou conference, then the integration of the JWT plugin went wrong.

As of now, the latest available version stands at 0.78.x, where the Enterprise features are readily accessible without the need for a license key. Typically, there shouldn't be any disparities within the JWT section between versions.

Are you utilizing the planned conferences or accessing the public rooms, which can be reached by adding a trailing /m/?

**Comment by baby-leo** [comment]
with out the app id and password, my jitsi meet is not accessible and is asking me for those credentials

**Comment by holema** [comment]
Hello @baby-leo,
can you send me the conference link or invite me with the email entwicklung@h2-invent.com. Then I can test the link.

Best regards

**Comment by baby-leo** [comment]
i have purge every thing and reinstalled it, and now it is working. thanks for the help
