### ISSUE TITLE
facing problem while installing 

### ISSUE THREAD

**Issue by 297297sid** [H2-invent/jitsi-admin#496]
after following this cd ~
wget https://github.com/H2-invent/jitsi-admin/raw/master/install.sh
sudo bash install.sh , i m not able to see UI when i am accessing my base url provided during installation

**Comment by holema** [comment]
Hello @297297sid,
I will check the installation routine

**Comment by holema** [comment]
Hello @297297sid,

just tested the installer. It is working as expected. What is the error you are facing?

**Comment by 297297sid** [comment]
after this i am clicking to homepage and it takes me to keycloak page and after entering credential it takes me to https://newadmin.cdac.in/login/keycloak_login/check?state=ba444c9618b5d7023e65e9bc9a42fcdc&session_state=e9b3b2ce-53b8-46bb-9276-d6cf2ff6e02b&code=d0fc1f95-1417-4d65-9945-39eb6c6ace3e.e9b3b2ce-53b8-46bb-9276-d6cf2ff6e02b.0d8853e0-f379-4c8e-96e4-575f0c088685 telling connection refused

**Comment by holema** [comment]
Hello @297297sid,

I realize that you have http in the screenshot and https in the url you post.
That's why the page is unreachable after login.

If you want to use the jitsi-admin in a http environment, you have to set the jitsi admin in development mode.

**Comment by holema** [comment]
Please check this branch out:
https://github.com/H2-invent/jitsi-admin/tree/hotfix/keycloak-redirect-uri

and try it out.

**Comment by 297297sid** [comment]
![Screenshot from 2023-12-11 16-13-09](https://github.com/H2-invent/jitsi-admin/assets/97450680/09f0e81c-18aa-49a0-a5a9-22424491db04)
facing same issue after passing cresdential it redirect to 
http://newadmin.cdac.in/xyz/login/keycloak_login/check?state=dc10d412ca0809cc44e6b5121b261c3e&session_state=f05cf9d1-8ab2-4734-b867-f089b53a44a4&code=9edc15db-c28b-4b84-b1b3-ea402696699f.f05cf9d1-8ab2-4734-b867-f089b53a44a4.0d8853e0-f379-4c8e-96e4-575f0c088685

**Comment by 297297sid** [comment]
COULD YOU PLEASE CLEARLY TELL ME STEPS FOR THIS SETUP

**Comment by holema** [comment]
Hello @297297sid,

Please try this branch.
https://github.com/H2-invent/jitsi-admin/tree/hotfix/keycloak-redirect-uri-https

**Comment by holema** [comment]
Schould be fixed with #498
