### ISSUE TITLE
How to I uninstall 

### ISSUE THREAD

**Issue by gpahlevanzadeh** [H2-invent/jitsi-admin#502]
I need to uninstall completely, How can I do it?

**Comment by holema** [comment]
Hello, do you use the docker installation or the plain installation?

**Comment by gpahlevanzadeh** [comment]
plain.

**Comment by gpahlevanzadeh** [comment]
by the way install.sh is very dirty, Do you have any deb file or another package? or clean compiling for jitsi-admin ?

**Comment by holema** [comment]
Hello @gpahlevanzadeh,

I´m very pleased to help you. The application is a normal web application with it's root directory in /var/www.
To unintall just remove this directory.

Why do you think the install script is dirty? It is only copying the files to the correct localtion. You can support the project by creating a new and better install script.

We always suggest the docker version wich is very easy to install and brings all parts of the jitsi-admin in one docker file. It is also an one click installer with the docker included.
https://github.com/H2-invent/jitsi-admin/wiki/Install-jitsi-admin-in-docker

We do have a debian package but up to now not for the public usage.

**Comment by gpahlevanzadeh** [comment]
I installed however I will ask problem in another thread.
