### ISSUE TITLE
grafana and conflict port

### ISSUE THREAD

**Issue by gpahlevanzadeh** [H2-invent/jitsi-admin#504]
Default port of grafana is 3000 and your websocket is adjusted for listen to port 3000.

**Comment by holema** [comment]
Hello @gpahlevanzadeh 

thanks for your input. The default port for NodeJs is 3000 so t that's the reason why we use port 3000.
YOu can set the port for the websocket by adding the PORT attribute to the service file. The service file should be here:  EnvironmentFile=/etc/systemd/system/jitsi-admin.conf
here just add the line: 
`PORT=<your port number>`
