### ISSUE TITLE
another authentication 

### ISSUE THREAD

**Issue by gpahlevanzadeh** [H2-invent/jitsi-admin#505]
my jitsi is on XMMP and I disabled JWT, and documentation of jitsi-admin is set to JWT and token. I don't want to use token, Please help me....
I don't use docker, I opened install.sh and by hand run it's commands.

**Comment by holema** [comment]
If you don't want to use JWT authentication you can just leave  the app-ID and app secret in the server settings blank. Than no JWT is created and used.

**Comment by gpahlevanzadeh** [comment]
your server configuration file means .env.prod.local ? I'm beginner in jitsi-admin and some of docs is in German.

**Comment by holema** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}                                                                                                                                               Exactly. There is the websocket url and there should be the port changed                                                                                                                                                                           Von: ***@***.***: 3. Januar 2024 14:06An: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [H2-invent/jitsi-admin] another authentication  (Issue #505)  
your server configuration file means .env.prod.local ? I'm beginner in jitsi-admin and some of docs is in German.

**Comment by gpahlevanzadeh** [comment]
I didn't find app-ID and app in .env.prod.local, Where can I change thme? in which file?

**Comment by holema** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}After installing the jitsi Admin you can add Jitsi servers via GUI. There you can set the apd id and app secret. So first get the jitsi Admin running and then go the GUI and setup your jitsi server there                                                                                                                                                                          Von: ***@***.***: 3. Januar 2024 14:45An: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [H2-invent/jitsi-admin] another authentication  (Issue #505)  
I didn't find app-ID and app in .env.prod.local, Where can I change thme? in which file?

**Comment by gpahlevanzadeh** [comment]
wow, I did reverse, I setup jistsi, prosydy and jicof, And now I have a stable system of jitsi on Debian Stable, Then I started jitsi-admin.

**Comment by holema** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  This is all good. You will need your installed jitsi Admin. The jitsi Admin will not set up your jitsi server. It is only a guard to protect you conferences. So go ahead and then when the jitsi Admin ist working you will see that you only need to enter the URL of you jitsi installation. You don't need any app id or app secret. Just the url of your Jitsi Server                                                                                                                                              Gesendet über BlackBerry Hub+ Posteingang für Android                                                                                                                                                                           Von: ***@***.***: 3. Januar 2024 15:35An: ***@***.***: ***@***.***: ***@***.***; ***@***.***: Re: [H2-invent/jitsi-admin] another authentication  (Issue #505)  
wow, I did reverse, I setup jistsi, prosydy and jicof, And now I have a stable system of jitsi on Debian Stable, Then I started jitsi-admin.

**Comment by gpahlevanzadeh** [comment]
After weekend i comeback to my work place.I  setup a new VM and install jitsi-admin with the following URL:
http://admin.mydomain.TLD/ in the following variables in .env.prod.local:
MERCURE_PUBLIC_URL
VICH_BASE
laF_URL
and DATABASE‌_URL‌ set to my db, and MAILER_DNS‌ and DEFAULT_DN set to the given values.
And I comment all of variables, Now when i open http://admin.mydomain.tld/ It's redirected to www.dummy.com/realms/dummy/protocols/openid-connect/auth?redirect_uri=http://admin.mydomain.TLD/login%20Fkeycloack_login%20Fcheck&scop=email%20openid%20profile&state=a8208ce1af49dsdssdsddsdds&response_type=code&approval_prompt=auto&client_id=dummy

I can't understand why domain changed.

**Comment by gpahlevanzadeh** [comment]
Unfortuenatly my websocket can't run, with ss -atn |grep 3000 I don't havre any result.

**Comment by gpahlevanzadeh** [comment]
I install module express for node and websocket is running, But I get error 404.

**Comment by holema** [comment]
> After weekend i comeback to my work place.I setup a new VM and install jitsi-admin with the following URL: http://admin.mydomain.TLD/ in the following variables in .env.prod.local: MERCURE_PUBLIC_URL VICH_BASE laF_URL and DATABASE‌_URL‌ set to my db, and MAILER_DNS‌ and DEFAULT_DN set to the given values. And I comment all of variables, Now when i open http://admin.mydomain.tld/ It's redirected to [www.dummy.com/realms/dummy/protocols/openid-connect/auth?redirect_uri=http://admin.mydomain.TLD/login%20Fkeycloack_login%20Fcheck&scop=email%20openid%20profile&state=a8208ce1af49dsdssdsddsdds&response_type=code&approval_prompt=auto&client_id=dummy](http://www.dummy.com/realms/dummy/protocols/openid-connect/auth?redirect_uri=http://admin.mydomain.TLD/login%20Fkeycloack_login%20Fcheck&scop=email%20openid%20profile&state=a8208ce1af49dsdssdsddsdds&response_type=code&approval_prompt=auto&client_id=dummy)
> 
> I can't understand why domain changed. And When I uncomment OAUTH* I get 404 for this url: http://admin.mydomain.tld/realms/jitsi-admin/protocol/openid-connect/auth?redirect_uri=http%3A%2F%2Fadmin.meet.icro.ir%2Flogin%2Fkeycloak_login%2Fcheck&scope=email%20openid%20profile&state=402173fe7477e4bba77e5d01aec0e03b&response_type=code&approval_prompt=auto&client_id=

You need to set these variables in your env too:
```
###> hwi/oauth-bundle ###
OAUTH_KEYCLOAK_CLIENT_ID=dummy
OAUTH_KEYCLOAK_CLIENT_SECRET=dummy
OAUTH_KEYCLOAK_SERVER=http://dummy
OAUTH_KEYCLOAK_REALM=dummy
###< hwi/oauth-bundle ###
```

These are the settings for the keycloak server

**Comment by gpahlevanzadeh** [comment]
I don't want to use keycloak, How can implement it? by the way , I install with `npm install express` and websocket is running.

**Comment by holema** [comment]
Jitsi Admin is build to work with keycloak. The JItsi-Admin does not bring any user managment. It relies on the keycloak, because keycloak is compatible to the most other IAM asystems.

You should only do `npm install` in the websocket directory, because express is already configured in the corrext version. BUt if it works then everything is great.

**Comment by gpahlevanzadeh** [comment]
If you remember, I used XMMP, not JWT. can I combine together?

**Comment by holema** [comment]
But you need a login window and this is created from the keycloak

**Comment by holema** [comment]
at the keycloak. And then the keycloak makes all the user organisation for you
