### ISSUE TITLE
8080 and stats of jitsi

### ISSUE THREAD

**Issue by gpahlevanzadeh** [H2-invent/jitsi-admin#506]
jitsi itself open 8080 and generates as json into http://jitsi:8080/colibri/stats 
Now I saw port 8080 in your Nginx file, I confused.

**Comment by holema** [comment]
Hello @gpahlevanzadeh ,
That's true. We already prepared the nginx conf to work as a reverseproxy for the keycloak IAM server. If you use an external keycloak you can remove this line in the nginx conf.
