### ISSUE TITLE
doubt

### ISSUE THREAD

**Issue by ReshmaJaiswal** [H2-invent/jitsi-admin#510]
how to integrate electron desktop app with this jitsi admin panel

**Comment by holema** [comment]
Hello, within the Jitsi admin interface, you have the option to choose whether to initiate the conference in the browser or in the Electron app from the dashboard. Opting to start the conference in the app generates a deep link, redirecting the browser to open the link within the Electron app.

**Comment by ReshmaJaiswal** [comment]
Regarding the process of redirecting the browser to open a link within the Electron app, I would like to inquire about the mechanism by which the system identifies the Electron app's opening steps. It seems plausible that the configuration for this behavior could be located in various places. Could you elaborate on how the system specifically ensures that the link opens within the Electron app?

**Comment by holema** [comment]
Hello, I don't know what you want to achive, wo it is realy hard to understand the usecase.

**Comment by ReshmaJaiswal** [comment]
I am kust asking where ur deeplinks configuration are mentioned so that it chooses electron app ,somewhere u have mentioned electron app configuration?where it is????

**Comment by ReshmaJaiswal** [comment]
$res['joinBrowser'] = $this->urlGenerator->generate('room_join', ['t' => 'b', 'room' => $room->getId()], UrlGenerator::ABSOLUTE_URL);
        $res['joinApp'] = $this->urlGenerator->generate('room_join', ['t' => 'a', 'room' => $room->getId()], UrlGenerator::ABSOLUTE_URL);
 i dont understand how admin knows? and how it open electron app ??

**Comment by holema** [comment]
Hello @ReshmaJaiswal,

If join in app is selected, then the jitsi-admin redirects to an internal join page and sets the parameter t to "a". The jisi-admin will then redirect to a new windwo but there it will not add an "https://" infront of the url but a "jitsi-meet://". The browser now knows that it should open the link with the jitsi-meet app.

**Comment by ReshmaJaiswal** [comment]
yea,but i am asking app configuration are mentioned anywhere in code ?if user want that any other app might open then ?where we can see that specific this app will open in code
