### ISSUE TITLE
Participants from outside organization have to log in when they join conference from invitation link

### ISSUE THREAD

**Issue by rfkarpinski** [H2-invent/jitsi-admin#514]
**Describe the bug**
When I've created conference with unchecked **Only signed up users can join this conference.** users joining from invitation link gets login page to keycloak.

**To Reproduce**
1. Go to 'Plan a conference'
2. Leave **Only signed up users can join this conference.** unchecked.
3. Add participants
4. See login page for participants outside organization

**Branch or Version you using**
```
(2) root@app:/var/www/jitsi-admin on master [!]
# git branch                                                   
* master

(2) root@app:/var/www/jitsi-admin on master [!]
# git describe --tags
0.79.5

```

**Expected behavior**
Users outside organization doesn't have to login to keycloak.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 38
 - Browser Brave
 - Version v1.62.165

**Additional context**
Selfhosted instalation on Debian 12. No docker.

**Comment by holema** [comment]
Hello @rfkarpinski,
thanks for the good isssue.

Can you double check in your .env.local file the paramter `laF_onlyRegisteredParticipents=0` This paramter must be set to 0

**Comment by rfkarpinski** [comment]
There You go :)

```
(2) root@app:/var/www/jitsi-admin on master [!] took 40s
# grep laF_onlyRegisteredParticipents .env.local 
laF_onlyRegisteredParticipents=0


```

**Comment by holema** [comment]
@rfkarpinski I close it, as we tested it yesterday
