### ISSUE TITLE
websocket issue

### ISSUE THREAD

**Issue by ReshmaJaiswal** [H2-invent/jitsi-admin#519]
i am getting this error again and again , "websocket error there is no real time communication at moment .please reload page" after some tme of loading page
also when i schedule a conference and press on save button it take toooo much time to save it continously show loading icon and then i have to press on cross icon it takes too much time to save conference or edit it .

**Comment by holema** [comment]
Hello, did you install the jitsi admin with docker or with plain?

**Comment by HighwayStar** [comment]
Also have this issue with plain install. Browser Network console doesnt show any ws issue

**Comment by ReshmaJaiswal** [comment]
plain install

**Comment by holema** [comment]
Hello @HighwayStar and @ReshmaJaiswal,

plain installation is always complex to find. Did you install the jitsi admin with the install script?

Ist the websocket service running? you can check this with `systemctl jitsi-admin_websocket.service status` to check if the service is started.

**Comment by holema** [comment]
hello @HighwayStar,

a double nginx proxy can always lead to a problem. You can proxy from your original nginx directly to the port3000 on the jitsi admin server

**Comment by ReshmaJaiswal** [comment]
![Screenshot from 2024-04-15 10-38-51](https://github.com/H2-invent/jitsi-admin/assets/158130522/5e26057f-6425-442b-a4b4-d5c0105efff4)
here i am getting issue while saving conference it takes too long time.

**Comment by HighwayStar** [comment]
> hello @HighwayStar,
> 
> a double nginx proxy can always lead to a problem. You can proxy from your original nginx directly to the port3000 on the jitsi admin server

This is what I've tried first. I moved 
```
location /ws/.well-known/mercure {
...
}

location /ws {
...
}

location /.well-known/mercure {
...
}
```
to my front nginx, but still getting ws error. Do I need to change jitsi-admin-websocket service settings?

**Comment by HighwayStar** [comment]
And are there logs to see for the root of the problem? When I see websocket error in browser I cant see any network error in browser developer console to see what url it actually missing.

**Comment by ReshmaJaiswal** [comment]
:/var/www/jitsi-admin$ sudo systemctl restart jitsi-admin_websocket.service 
:/var/www/jitsi-admin$ sudo systemctl status jitsi-admin_websocket.service 
● jitsi-admin_websocket.service - Jitsi-Admin Websocket Service
     Loaded: loaded (/etc/systemd/system/jitsi-admin_websocket.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2024-04-15 11:04:56 IST; 476ms ago
    Process: 1081945 ExecStart=node . (code=exited, status=1/FAILURE)
   Main PID: 1081945 (code=exited, status=1/FAILURE)
        CPU: 859ms
:/var/www/jitsi-admin$ sudo systemctl start jitsi-admin_websocket.service 
:/var/www/jitsi-admin$ sudo systemctl status jitsi-admin_websocket.service 
● jitsi-admin_websocket.service - Jitsi-Admin Websocket Service
     Loaded: loaded (/etc/systemd/system/jitsi-admin_websocket.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Mon 2024-04-15 11:05:13 IST; 1s ago
    Process: 1081996 ExecStart=node . (code=exited, status=1/FAILURE)
   Main PID: 1081996 (code=exited, status=1/FAILURE)
        CPU: 590ms
reshma@admin:/var/www/jitsi-admin$

**Comment by holema** [comment]
Hello @ReshmaJaiswal, the infinite turning of the icon is a sign that the jisti admin backend is also not able to send a message through the websocket to the clients.

@HighwayStar What is your complete nginx config?

**Comment by holema** [comment]
@ReshmaJaiswal please send me a screensjhot of the service status

**Comment by ReshmaJaiswal** [comment]
I am not getting anything according to ut instruction page i done setup :-  https://github.com/H2-invent/jitsi-admin/wiki/Websocket-installation

now i have 2 websocket service
 s@adminclone:/var/www/jitsi-admin$ sudo systemctl status jitsi-admin-websocket.service
● jitsi-admin-websocket.service - Jitsi-Admin Websocket Service
     Loaded: loaded (/etc/systemd/system/jitsi-admin-websocket.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-04-08 10:28:51 IST; 1 week 1 day ago
   Main PID: 932562 (node)
      Tasks: 11 (limit: 9389)
     Memory: 28.1M
        CPU: 28.916s
     CGroup: /system.slice/jitsi-admin-websocket.service
             └─932562 node .

Apr 08 10:28:51 xyz.cd.in systemd[1]: Started Jitsi-Admin Websocket Service.
s@adminclone:/var/www/jitsi-admin$ cd ..
s@adminclone:/var/www$ cd ..
s@adminclone:/var$ cd ..
s@adminclone:/$ sudo systemctl status jitsi-admin-websocket.service
● jitsi-admin-websocket.service - Jitsi-Admin Websocket Service
     Loaded: loaded (/etc/systemd/system/jitsi-admin-websocket.service; enabled; vendor preset: enabled)
     Active: active (running) since Mon 2024-04-08 10:28:51 IST; 1 week 1 day ago
   Main PID: 932562 (node)
      Tasks: 11 (limit: 9389)
     Memory: 28.1M
        CPU: 28.917s
     CGroup: /system.slice/jitsi-admin-websocket.service
             └─932562 node .

Apr 08 10:28:51 xyz.cd.in systemd[1]: Started Jitsi-Admin Websocket Service.
s@adminclone:/$ sudo systemctl status jitsi-admin_websocket.service
× jitsi-admin_websocket.service - Jitsi-Admin Websocket Service
     Loaded: loaded (/etc/systemd/system/jitsi-admin_websocket.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-04-15 11:15:39 IST; 24h ago
    Process: 1082377 ExecStart=node . (code=exited, status=1/FAILURE)
   Main PID: 1082377 (code=exited, status=1/FAILURE)
        CPU: 610ms

Apr 15 11:15:39 xyz.p.cd.in systemd[1]: jitsi-admin_websocket.service: Scheduled restart job, restart counter is at 4.
Apr 15 11:15:39 xyz.p.cd.in systemd[1]: Stopped Jitsi-Admin Websocket Service.
Apr 15 11:15:39 xyz.p.cd.in systemd[1]: jitsi-admin_websocket.service: Start request repeated too quickly.
Apr 15 11:15:39 xyz.p.cd.in systemd[1]: jitsi-admin_websocket.service: Failed with result 'exit-code'.
Apr 15 11:15:39 xyz.p.cd.in systemd[1]: Failed to start Jitsi-Admin Websocket Service.
s@adminclone:/$ cd /opt
s@adminclone:/opt$ ls
jitsi-admin-websocket
s@adminclone:/opt$ cd ..
s@adminclone:/$ cd /var/www/jitsi-admin
s@adminclone:/var/www/jitsi-admin$ ls
appendFormData.php  crowdin.yml                 documentation           jitsi-admin_messenger.service  phpDocumentor.phar    repairLog.txt  update_instruction_0.72.x...0.73.x.md
assets              debian_installer            drivers                 jstests                        phpstan.neon          SECURITY.md    update_instruction_0.73.x...0.74.x.md
bin                 docker                      formdatafinal.json      LICENSE                        phpunit.xml.dist      src            update_instruction_0.74.x...0.75.x.md
BranchPipeline.sh   docker-compose.cluster.yml  installDockerDebian.sh  migrations                     phpunit.xml.dist.bak  symfony.lock   update_instruction_0.75.x...0.76.x.md
code_of_conduct.md  docker-compose.test.yml     installDocker.md        nodejs                         public                templates      update_instruction_0.76.x...0.77.x.md
composer.json       docker-compose.yml          installDocker.sh        node_modules                   README_de.md          tests          update_instruction_0.78.x...0.79.x.md
composer.lock       Dockerfile                  installDockerUbuntu.sh  package.json                   README.md             theme          var
composer.phar       dockerupdate.sh             installer               package-lock.json              rector.php            traefik        vendor
config              docs                        install.sh              phpcs.xml.dist                 RELEASE_NOTE.md       translations   webpack.config.js
s@adminclone:/var/www/jitsi-admin$ cd src
s@adminclone:/var/www/jitsi-admin/src$ ls
Command  Controller  DataFixtures  dataType  Entity  Exceptions  Form  Helper  Kernel.php  Message  MessageHandler  Migrations  Repository  Security  Service  Twig  Util  UtilsHelper.php
s@adminclone:/var/www/jitsi-admin/src$ cd ..
s@adminclone:/var/www/jitsi-admin$ cd ..
s@adminclone:/var/www$ cd jitsi-admin
s@adminclone:/var/www/jitsi-admin$ cd installer/
s@adminclone:/var/www/jitsi-admin/installer$ ls
jitsi-admin.conf  jitsi-admin_messenger.service  jitsi-admin_websocket.service  nginx.conf
s@adminclone:/var/www/jitsi-admin/installer$

**Comment by ReshmaJaiswal** [comment]
pls help

**Comment by holema** [comment]
Hello @ReshmaJaiswal,
please contact me on entwicklung@h2-invent.com this is not an technical issue, because the websocket is working and a proxying of several nginx proxies is always a diffucult thing.  We should take a look on your problem.

**Comment by ReshmaJaiswal** [comment]
just clear one thing 2 websocket service are running for single admin panel???

**Comment by ReshmaJaiswal** [comment]
no websocket is not working s@adminclone:/$ sudo systemctl status jitsi-admin_websocket.service
× jitsi-admin_websocket.service - Jitsi-Admin Websocket Service
Loaded: loaded (/etc/systemd/system/jitsi-admin_websocket.service; enabled; vendor preset: enabled)
Active: failed (Result: exit-code) since Mon 2024-04-15 11:15:39 IST; 24h ago
Process: 1082377 ExecStart=node . (code=exited, status=1/FAILURE)
Main PID: 1082377 (code=exited, status=1/FAILURE)
CPU: 610ms

Apr 15 11:15:39 xyz.p.cd.in systemd[1]: jitsi-admin_websocket.service: Scheduled restart job, restart counter is at 4.
Apr 15 11:15:39 xyz.p.cd.in systemd[1]: Stopped Jitsi-Admin Websocket Service.
Apr 15 11:15:39 xyz.p.cd.in systemd[1]: jitsi-admin_websocket.service: Start request repeated too quickly.
Apr 15 11:15:39 xyz.p.cd.in systemd[1]: jitsi-admin_websocket.service: Failed with result 'exit-code'.
Apr 15 11:15:39 xyz.p.cd.in systemd[1]: Failed to start Jitsi-Admin Websocket Service.
s@adminclone:/$ cd /opt

**Comment by holema** [comment]
no there should only run one service.
Your logs shows that the service is not working

**Comment by ReshmaJaiswal** [comment]
I am not getting anything according to your instruction page i done setup :- https://github.com/H2-invent/jitsi-admin/wiki/Websocket-installation and 1 websocket is already there in code ?????what should i do now

**Comment by ReshmaJaiswal** [comment]
which websocket i should go with???? in file one or /opt one??

**Comment by holema** [comment]
hello @ReshmaJaiswal Didi you get the websock to run now?

**Comment by ReshmaJaiswal** [comment]
no ,which websocket i should go with???? in file one or /opt one??

**Comment by rutujasm** [comment]
> ![Screenshot from 2024-04-15 10-38-51](https://private-user-images.githubusercontent.com/158130522/322358704-5e26057f-6425-442b-a4b4-d5c0105efff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzgyNTQsIm5iZiI6MTcxNzQ3Nzk1NCwicGF0aCI6Ii8xNTgxMzA1MjIvMzIyMzU4NzA0LTVlMjYwNTdmLTY0MjUtNDQyYi1hNGI0LWQ1YzAxMDVlZmZmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudG

lhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwNTEyMzRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02N2Y0YmNiNTYyMDQwODIzZTU5MDJhMWQ4M2Y1NzE5OTU2ZmUwMmU4NDAxOTFjNWI2ODJjZmNkMjAyOTE5Mjk4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.SqM9oy71JgqF_zf5nWDS2LoqArN-tM9Jmd-SgdICsBU) here i am getting issue while saving conference it takes too long time.

Facing same issue .How to solve this ? Please reply.

Thank you.

**Comment by rutujasm** [comment]
> ![Screenshot from 2024-04-15 10-38-51](https://private-user-images.githubusercontent.com/158130522/322358704-5e26057f-6425-442b-a4b4-d5c0105efff4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0NzgzNTUsIm5iZiI6MTcxNzQ3ODA1NSwicGF0aCI6Ii8xNTgxMzA1MjIvMzIyMzU4NzA0LTVlMjYwNTdmLTY0MjUtNDQyYi1hNGI0LWQ1YzAxMDVlZmZmNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNFQwNTE0MTVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05MGFkN2VlODhiZjU4ZWJmODdlMTYxNDgwYWJlZTA5MzdmM2VhMWYzMGUwZTVlYTFmMGViNjI1YTNmMmUxMzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hzpOYiIyo70c7yAaYWjfbTwh3oQ9Ae15aCj5KAWxMwI) here i am getting issue while saving conference it takes too long time.

Facing same issue .How to solve this ? Please reply.

Thank you.

**Comment by holema** [comment]
Hello @rutujasm ,
Die you install ist with docker or plain?
If plain do you use a reverse proxy in front of the jitsi admin.
The long waiting means that the websocket service ist not accessable from the jitsi admin service. So he keeps trying to access the websocket service.

**Comment by rutujasm** [comment]
Its a plain installation and my setup is in local nginx.It does't have any proxy above this.
this is my jitsi-admin.conf
location /ws/.well-known/mercure {
    proxy_pass http://127.0.0.1:3000/.well-known/mercure;
    proxy_set_header Host $host;
    proxy_set_header X_Real_IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
}

location /ws {
    proxy_pass http://127.0.0.1:3000/ws;
    proxy_set_header Host $host;
    proxy_set_header X_Real_IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_read_timeout 600;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
}

location /.well-known/mercure {
    proxy_pass http://127.0.0.1:3000/.well-known/mercure;
    proxy_set_header Host $host;
    proxy_set_header X_Real_IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

    proxy_read_timeout 600;
    proxy_connect_timeout 600;
    proxy_send_timeout 600;
}

**Comment by rutujasm** [comment]
Waiting for your reply.Please help.
