### ISSUE TITLE
Cannot Load Dashboard In Default Docker Dev Install

### ISSUE THREAD

**Issue by BinaryWizard904** [H2-invent/jitsi-admin#526]
I have been trying to get a dev copy of jitsi-admin working but haven't been able to even get to the dashboard.  My current steps:

1. Install Docker CE.
2. Clone repo
3. Edit ./installDocker.sh to replace "docker-compose" commands with "docker compose" so they work with Docker's built-in compose command.
4. Run ./installDocker.sh with the following options:
    - ENVIRONMENT: dev
    - HTTP_METHOD: http
    - PUBLIC_URL: localhost
    - All email settings are the defaults.
5. Wait for all containers to finish starting up.
6. Observe that only some URLs work
    - Working
        - http://localhost/keycloak
    - Partially Working
        - http://localhost — All buttons that redirect to the dashboard fail.  They return the keycloak "We are sorry... page not found" error page.
            - Example URL of the Login Button: `http://localhost/keycloak/realms/jitsiadmin/protocol/openid-connect/auth?redirect_uri=http%3A%2F%2Flocalhost%2Flogin%2Fkeycloak_login%2Fcheck&scope=email%20openid%20profile&state=20fa54e385fb33dbd0a041aef3eb2583&response_type=code&approval_prompt=auto&client_id=jitsiadmin`
    - Broken
        - http://localhost/room/dashboard — Returns Keycloak "We are sorry... page not found" error page
        - http://localhost/traefik — Returns Symfony Exception page error "No route found for 'GET http://localhost/traefik'"

Really not sure what is going wrong here.  Is there some step not mentioned on the [Install jitsi admin in docker](https://github.com/H2-invent/jitsi-admin/wiki/Install-jitsi-admin-in-docker) wiki page?

**Comment by holema** [comment]
Hello,

I found the bug. The dev environment normaly was only created for our internal development so it was not maintained after the keycloak migration to keycloak 22. Therefor there ist a hostname issue. I try to fix it and then I will send you a ping. I think I will fix it tomorrow.

**Comment by holema** [comment]
hello @BinaryWizard904 

the bug is closed.
To install the new version do:
`git pull`
`docker-compose down -v` to remove also the volumes
`bash installDocker.sh` to install the and rebuild the container
