### ISSUE TITLE
facing problem in enabling jwt 

### ISSUE THREAD

**Issue by ReshmaJaiswal** [H2-invent/jitsi-admin#531]
when we generate token it receives to moderator as well as participant and entry link guest participant ?right what if i need to send token only to the moderator ?? please tell me once flow if i want to activate jwt for server then what should i have to fill in the form?as i am not much clear about application jwt functionality ,please help..........

**Comment by holema** [comment]
I moved this into discussions. this is not an issue. We can discuss this in the discussions
