### ISSUE TITLE
JitsiMeetExternalAPI is not defined

### ISSUE THREAD

**Issue by baby-leo** [H2-invent/jitsi-admin#547]
i am getting an error that says Uncaught ReferenceError: JitsiMeetExternalAPI is not defined when i try to start a meeting in the same browser tab and when the participant is in waiting is and gets approved. how can i solve this issue

**Comment by holema** [comment]
Hello, this meany that the jitsi Url you set up is not correct. Please double check your jitsi meet URL. It is importent not to set the https in front of the server

**Comment by baby-leo** [comment]
yes, i have not put the https in the front, i have only enterd the url and , when i enable the cors-header i do not see this problem

**Comment by holema** [comment]
Hallo @baby-leo,
you already found the solution. you are setting the cors header in your server. So your jitsi admin is not allowed to include the iframe from your jitsi meet domain. There are two solution, add a wildcard "*" to the cors header or remove the header from the response.

**Comment by holema** [comment]
the jitsi admin tries to start the jitsi meeting in an iframe. It opens the jitsi admin only in a new tab when the cors header is set an the url of your jitsi admin is not set in your cors header correctly.

**Comment by baby-leo** [comment]
i have tried that, the problem i am facing is that when a participant in a waiting list is accepted, it does not open the meeting in a new tab end it shows me a warning saying the script can not colse a tab, abd bring them back to the login page, instade of to the meeting

**Comment by baby-leo** [comment]
here is my error i get to be specific
`Uncaught (in promise) TypeError: Failed to fetch
    at window.fetch (uyutf-950:472:16254)
    at B (lobbyParticipant.b732bbe9.js:2:13962)
    at window.onbeforeunload (lobbyParticipant.b732bbe9.js:2:14173)
    at lobbyParticipant.b732bbe9.js:2:14062
uyutf-950:472 
        
        
       Uncaught (in promise) TypeError: Failed to fetch
    at window.fetch (uyutf-950:472:16254)
    at B (lobbyParticipant.b732bbe9.js:2:13962)
    at window.onbeforeunload (lobbyParticipant.b732bbe9.js:2:14173)
    at lobbyParticipant.b732bbe9.js:2:14062
620.817b65ee.js:2 Uncaught TypeError: r[e] is not a function
    at o (620.817b65ee.js:2:11696)
    at Object.success (lobbyParticipant.b732bbe9.js:2:16493)
    at u (723.3cd42e34.js:2:37550)
    at Object.fireWith [as resolveWith] (723.3cd42e34.js:2:38298)
    at S (723.3cd42e34.js:2:89415)
    at XMLHttpRequest.<anonymous> (723.3cd42e34.js:2:91883)`

**Comment by holema** [comment]
HEllo @baby-leo,
this sounds strange.
Can you retry to reinstall the jitsi admin when you started it with docker by typing `bash installDocker.sh`
