### ISSUE TITLE
Custom text for emails

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#70]
Another Thing is to change the text of the emails. It would be great to add additional links and individual texts. Maybe the agenda field can be used for this, but I don't know if html is allowed there?

**Comment by holema** [comment]
The Agenda Field can up to now not be used to write HTML. Every HTML will be escaped. But we will discuss if it is a sucurity issue if there can be HTML.

**Comment by xdaniel2063** [comment]
This works, thanks a lot. Where can I find the description of the markdown?
