### ISSUE TITLE
transfer moderator

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#71]
Another feature I'm looking for, is to transfer the moderation rights to someone else in my team?

**Comment by holema** [comment]
The idea is good, but if you shoose the move the moderator role of the room to a participant, you still want to be the owner of the room? Or do you realy want to transfer the room to someone else?

**Comment by xdaniel2063** [comment]
The idea is: If I have planed a lesson and become ill, can another organisator of my server get the moderators role?
