### ISSUE TITLE
Auto generated form to register for a conference

### ISSUE THREAD

**Issue by xdaniel2063** [H2-invent/jitsi-admin#73]
I don't know how much work this is, but It could be a great enhancement to auto generate a form to register for an event.

**Comment by xdaniel2063** [comment]
and maybe a limit for participants.

**Comment by holema** [comment]
We add a feature, thats looks very similar to the requested Feature.
You can set the room to a public room. Then everyone can subscripe via a link.

**Comment by xdaniel2063** [comment]
Das sieht schon Klasse aus. Könnte man ggf. noch das Design der Anmeldeseite an das der Join-Seite anpassen und den Namen und Datum zu der Veranstaltung, zu der man/frau sich anmeldet einblenden?

**Comment by xdaniel2063** [comment]
Und das Teilnehmerlimit wäre noch toll. Nicht alle Server haben unbegrenzte Kapazitäten. Unser Server beispielsweise liegt irgendwo zwischen 20 und 30 Leuten.

Bei uns ist es so, dass die Gruppen in der Regel aus max 15 TN bestehen. Sich aber immer mehr Leute anmelden würden ...
