### ISSUE TITLE
Make screen-sharing configurable via JWT token

### ISSUE THREAD

**Issue by itrich** [H2-invent/jitsi-admin#77]
**Is your feature request related to a problem? Please describe.**
Zoombombing and sharing inappropriate videos has been a real issue within the last weeks. However, completely disallowing screen sharing for all guests isn't a pracitable solution either.

**Describe the solution you'd like**
A host should be able to decide whether or not he wants to allow screen sharing for guests or not. Moderators should always be allowed to share their screen. This can be realised via `enableFeaturesBasedOnToken:` and the feature `screen-sharing` within the JWT token.

**Describe alternatives you've considered**
Completely disabling screen sharing, which isn't practicable.

**Comment by holema** [comment]
Propably we can also add some more features to the JWT. 
We should check what else can be set by the JWT
